<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Amin Aina Shu">

<title>Final Survival Semiparametric</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Final Survival Semiparametric_files/libs/clipboard/clipboard.min.js"></script>
<script src="Final Survival Semiparametric_files/libs/quarto-html/quarto.js"></script>
<script src="Final Survival Semiparametric_files/libs/quarto-html/popper.min.js"></script>
<script src="Final Survival Semiparametric_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Final Survival Semiparametric_files/libs/quarto-html/anchor.min.js"></script>
<link href="Final Survival Semiparametric_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Final Survival Semiparametric_files/libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Final Survival Semiparametric_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Final Survival Semiparametric_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Final Survival Semiparametric_files/libs/bootstrap/bootstrap-1bc8a17f135ab3d594c857e9f48e611b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Final Survival Semiparametric</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Amin Aina Shu </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="checking-the-dataset" class="level2">
<h2 class="anchored" data-anchor-id="checking-the-dataset">Checking the dataset</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(haven)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'haven' was built under R version 4.4.3</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(survival)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'survival' was built under R version 4.4.3</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(survminer)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'survminer' was built under R version 4.4.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: ggplot2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'ggplot2' was built under R version 4.4.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: ggpubr</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'ggpubr' was built under R version 4.4.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'survminer'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:survival':

    myeloma</code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'dplyr'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:stats':

    filter, lag</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>data1 <span class="ot">&lt;-</span> <span class="fu">read_dta</span>(<span class="st">"C:/Users/amin9/OneDrive/R working directory/assignment prof kim drph1 sem 2/survival/semiparametric/stroke_fatality.dta"</span>)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="co"># View structure</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(data1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>tibble [226 × 49] (S3: tbl_df/tbl/data.frame)
 $ sex         : dbl+lbl [1:226] 2, 1, 2, 2, 1, 2, 2, 2, 1, 1, 2, 1, 2, 2, 1, 1, 2, 1, ...
   ..@ label       : chr "sex"
   ..@ format.stata: chr "%6.0f"
   ..@ labels      : Named num [1:2] 1 2
   .. ..- attr(*, "names")= chr [1:2] "male" "female"
 $ race        : dbl+lbl [1:226] 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
   ..@ label       : chr "race"
   ..@ format.stata: chr "%12.0f"
   ..@ labels      : Named num [1:6] 1 2 3 4 8 9
   .. ..- attr(*, "names")= chr [1:6] "malay" "chinese" "indians" "others" ...
 $ doa         : Date[1:226], format: "2011-01-01" "2011-01-03" ...
 $ dod         : Date[1:226], format: "2011-01-05" "2011-01-06" ...
 $ time        : num [1:226] 4 3 16 23 5 4 22 14 4 2 ...
  ..- attr(*, "label")= chr "time"
  ..- attr(*, "format.stata")= chr "%9.0g"
 $ time2       : num [1:226] 4 3 16 23 5 4 22 14 4 2 ...
  ..- attr(*, "label")= chr "time2"
  ..- attr(*, "format.stata")= chr "%9.0g"
 $ status2     : dbl+lbl [1:226] 2, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 2, 1, ...
   ..@ label       : chr "status at discharge"
   ..@ format.stata: chr "%5.0f"
   ..@ labels      : Named num [1:2] 1 2
   .. ..- attr(*, "names")= chr [1:2] "alive" "dead"
 $ gcs         : num [1:226] 15 15 15 11 15 7 5 13 15 15 ...
  ..- attr(*, "label")= chr "earliest Glasgow Coma Scale"
  ..- attr(*, "format.stata")= chr "%2.0f"
 $ sbp         : num [1:226] 150 152 231 110 199 190 145 161 222 161 ...
  ..- attr(*, "label")= chr "earliest systolic BP (mmHg)"
  ..- attr(*, "format.stata")= chr "%3.0f"
 $ dbp         : num [1:226] 87 108 117 79 134 101 102 96 129 107 ...
  ..- attr(*, "label")= chr "earliest diastolic BP (mmHg)"
  ..- attr(*, "format.stata")= chr "%3.0f"
 $ hr          : num [1:226] 92 87 64 90 72 63 102 81 72 94 ...
  ..- attr(*, "label")= chr "heart rate"
  ..- attr(*, "format.stata")= chr "%3.0f"
 $ dm          : dbl+lbl [1:226]  1, NA,  1,  8, NA,  2,  1,  1,  2,  2,  2,  2, NA, NA...
   ..@ label       : chr "diabetes"
   ..@ format.stata: chr "%3.0f"
   ..@ labels      : Named num [1:2] 0 1
   .. ..- attr(*, "names")= chr [1:2] "no" "yes"
 $ hpt         : dbl+lbl [1:226]  1,  1,  1,  1,  1,  2,  1,  1,  1,  2,  1,  2,  1,  1...
   ..@ label       : chr "hypertension"
   ..@ format.stata: chr "%3.0f"
   ..@ labels      : Named num [1:2] 0 1
   .. ..- attr(*, "names")= chr [1:2] "no" "yes"
 $ ckd         : dbl+lbl [1:226] NA, NA,  2,  8, NA,  2,  8,  2,  2,  2,  2,  2, NA, NA...
   ..@ label       : chr "chronic kidney disease"
   ..@ format.stata: chr "%3.0f"
   ..@ labels      : Named num [1:2] 0 1
   .. ..- attr(*, "names")= chr [1:2] "no" "yes"
 $ af          : dbl+lbl [1:226] NA, NA,  2,  8, NA,  2,  8,  2,  2,  2,  2,  2, NA, NA...
   ..@ label       : chr "atrial fibrillation"
   ..@ format.stata: chr "%3.0f"
   ..@ labels      : Named num [1:2] 0 1
   .. ..- attr(*, "names")= chr [1:2] "no" "yes"
 $ hd          : dbl+lbl [1:226] NA, NA,  2,  8, NA,  2,  8,  1,  2,  2,  2,  2, NA,  1...
   ..@ label       : chr "heart ds"
   ..@ format.stata: chr "%3.0f"
   ..@ labels      : Named num [1:2] 0 1
   .. ..- attr(*, "names")= chr [1:2] "no" "yes"
 $ dyslipid    : dbl+lbl [1:226] NA, NA,  1,  8, NA,  2,  8,  2,  2,  2,  2,  2, NA, NA...
   ..@ label       : chr "dyslipidemia"
   ..@ format.stata: chr "%3.0f"
   ..@ labels      : Named num [1:2] 0 1
   .. ..- attr(*, "names")= chr [1:2] "no" "yes"
 $ tia         : dbl+lbl [1:226] NA, NA,  2,  8, NA,  2,  8,  2,  2,  2,  2,  2, NA, NA...
   ..@ label       : chr "transient ischaemic attack"
   ..@ format.stata: chr "%3.0f"
   ..@ labels      : Named num [1:2] 0 1
   .. ..- attr(*, "names")= chr [1:2] "no" "yes"
 $ smoker      : dbl+lbl [1:226] NA, NA,  2,  8, NA,  2,  8,  2,  2,  1,  2,  2, NA, NA...
   ..@ label       : chr "smoking"
   ..@ format.stata: chr "%3.0f"
   ..@ labels      : Named num [1:2] 0 1
   .. ..- attr(*, "names")= chr [1:2] "no" "yes"
 $ hb          : num [1:226] 10.4 13 11 14.3 15.7 11.7 13.4 11.8 12.6 16.4 ...
  ..- attr(*, "label")= chr "hemoglobin"
  ..- attr(*, "format.stata")= chr "%4.1f"
 $ plat        : num [1:226] 249 156 179 233 351 133 290 251 196 188 ...
  ..- attr(*, "label")= chr "platelet"
  ..- attr(*, "format.stata")= chr "%5.1f"
 $ wbc         : num [1:226] 12.5 7.4 22.4 9.6 18.7 11.3 15.8 8.5 9 9.5 ...
  ..- attr(*, "label")= chr "total white cell count"
  ..- attr(*, "format.stata")= chr "%5.1f"
 $ na          : num [1:226] 138 132 135 132 138 140 134 135 129 137 ...
  ..- attr(*, "label")= chr "natrium"
  ..- attr(*, "format.stata")= chr "%5.1f"
 $ potas       : num [1:226] 3.6 4.1 4.7 3.8 3.8 3 4.1 4 4 3.7 ...
  ..- attr(*, "label")= chr "potassium"
  ..- attr(*, "format.stata")= chr "%4.1f"
 $ gluc        : num [1:226] NA 5.1 NA NA NA NA NA NA NA 5.5 ...
  ..- attr(*, "label")= chr "glucose"
  ..- attr(*, "format.stata")= chr "%4.1f"
 $ cbs         : num [1:226] 11.4 NA 18.6 6.8 6.5 8.4 13.4 14.9 6.6 5.8 ...
  ..- attr(*, "label")= chr "capillary blood sugar"
  ..- attr(*, "format.stata")= chr "%4.1f"
 $ chol        : num [1:226] NA 4.7 NA NA NA NA NA NA NA 6.9 ...
  ..- attr(*, "label")= chr "fasting tot chol(mmol/l)"
  ..- attr(*, "format.stata")= chr "%4.1f"
 $ tg          : num [1:226] NA 1.1 NA NA NA NA NA NA NA 1 ...
  ..- attr(*, "label")= chr "fasting TG (mmol/l)"
  ..- attr(*, "format.stata")= chr "%4.1f"
 $ urea        : num [1:226] 5.1 8.4 11 7.4 3.8 4 3.3 5.6 5.8 5.8 ...
  ..- attr(*, "label")= chr "urea"
  ..- attr(*, "format.stata")= chr "%4.1f"
 $ referral    : num [1:226] 4 4 4 3 1 2 4 3 3 4 ...
  ..- attr(*, "label")= chr "referral"
  ..- attr(*, "format.stata")= chr "%1.0f"
 $ transport   : num [1:226] 2 2 2 1 1 1 2 1 1 2 ...
  ..- attr(*, "label")= chr "transport"
  ..- attr(*, "format.stata")= chr "%1.0f"
 $ age2        : num [1:226] 69 64 63 67 66 78 55 65 67 56 ...
  ..- attr(*, "label")= chr "age in years"
  ..- attr(*, "format.stata")= chr "%10.0g"
 $ sex2        : dbl+lbl [1:226] 2, 1, 2, 2, 1, 2, 2, 2, 1, 1, 2, 1, 2, 2, 1, 1, 2, 1, ...
   ..@ label       : chr "sex"
   ..@ format.stata: chr "%10.0g"
   ..@ labels      : Named num [1:2] 1 2
   .. ..- attr(*, "names")= chr [1:2] "male" "female"
 $ marital2    : dbl+lbl [1:226] 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 1, 4, 4, 4, 3, 1, ...
   ..@ label       : chr "marital status"
   ..@ format.stata: chr "%10.0g"
   ..@ labels      : Named num [1:2] 0 1
   .. ..- attr(*, "names")= chr [1:2] "no" "yes"
 $ status1b    : dbl+lbl [1:226] 2, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 2, 1, ...
   ..@ label       : chr "status (alive, dead, etc)"
   ..@ format.stata: chr "%10.0g"
   ..@ labels      : Named num [1:4] 1 2 3 4
   .. ..- attr(*, "names")= chr [1:4] "alive" "dead" "others" "absconded"
 $ status2b    : dbl+lbl [1:226] 2, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 2, 1, ...
   ..@ label       : chr "status2b"
   ..@ format.stata: chr "%9.0g"
   ..@ labels      : Named num [1:2] 1 2
   .. ..- attr(*, "names")= chr [1:2] "alive" "dead"
 $ status3b    : dbl+lbl [1:226] 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, ...
   ..@ label       : chr "status @discharge 1=dead, 0=alive"
   ..@ format.stata: chr "%9.0g"
   ..@ labels      : Named num [1:2] 0 1
   .. ..- attr(*, "names")= chr [1:2] "alive" "dead"
 $ hpt2        : dbl+lbl [1:226]  1,  1,  1,  1,  1,  0,  1,  1,  1,  0,  1,  0,  1,  1...
   ..@ label       : chr "hpt2"
   ..@ format.stata: chr "%9.0g"
   ..@ labels      : Named num [1:2] 0 1
   .. ..- attr(*, "names")= chr [1:2] "no" "yes"
 $ marital3    : num [1:226] 1 1 1 1 1 1 1 1 1 1 ...
  ..- attr(*, "label")= chr "marital3"
  ..- attr(*, "format.stata")= chr "%9.0g"
 $ race2       : dbl+lbl [1:226] 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
   ..@ label       : chr "race2"
   ..@ format.stata: chr "%9.0g"
   ..@ labels      : Named num [1:2] 0 1
   .. ..- attr(*, "names")= chr [1:2] "no" "yes"
 $ sex3        : dbl+lbl [1:226] 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, ...
   ..@ label       : chr "male=1, female=0"
   ..@ format.stata: chr "%9.0g"
   ..@ labels      : Named num [1:2] 0 1
   .. ..- attr(*, "names")= chr [1:2] "female" "male"
 $ referral2   : num [1:226] 3 3 3 2 0 1 3 2 2 3 ...
  ..- attr(*, "label")= chr "referral2"
  ..- attr(*, "format.stata")= chr "%9.0g"
 $ referral2cat: dbl+lbl [1:226] 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, ...
   ..@ label       : chr "0 is hospital, 1=GP or home  or missing"
   ..@ format.stata: chr "%15.0g"
   ..@ labels      : Named num [1:2] 0 1
   .. ..- attr(*, "names")= chr [1:2] "hospital" "GP/Home/Missing"
 $ icd10cat    : dbl+lbl [1:226] 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, ...
   ..@ label       : chr "0=Cerebral Isch , 1=Haemorrhagic, 2= Other"
   ..@ format.stata: chr "%12.0g"
   ..@ labels      : Named num [1:3] 0 1 2
   .. ..- attr(*, "names")= chr [1:3] "CI,Others" "Haemorrhagic" "Others"
 $ icd10cat2   : dbl+lbl [1:226] 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, ...
   ..@ label       : chr "0=Cerebral Isch and others, 1=Haemorrhagic"
   ..@ format.stata: chr "%12.0g"
   ..@ labels      : Named num [1:2] 0 1
   .. ..- attr(*, "names")= chr [1:2] "CI,Others" "Haemorrhagic"
 $ icd10cat3   : dbl+lbl [1:226] 0, 0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 1, 1, ...
   ..@ label       : chr "0=Cerebral Isch or others, 1=SAH, 2=Haemorrhagic"
   ..@ format.stata: chr "%22.0g"
   ..@ labels      : Named num [1:3] 0 1 2
   .. ..- attr(*, "names")= chr [1:3] "CI,Others" "SAH" "ICB, Other Haemorrhage"
 $ dm2cat      : num [1:226] 1 0 1 0 0 0 1 1 0 0 ...
  ..- attr(*, "label")= chr "dm yes=1, no=0"
  ..- attr(*, "format.stata")= chr "%9.0g"
 $ hpt2cat     : num [1:226] 1 1 1 1 1 0 1 1 1 0 ...
  ..- attr(*, "label")= chr "hpt yes=1, no=0"
  ..- attr(*, "format.stata")= chr "%9.0g"
 $ dyslipid2cat: num [1:226] 0 0 1 0 0 0 0 0 0 0 ...
  ..- attr(*, "label")= chr "dyslipid yes=1, no=0"
  ..- attr(*, "format.stata")= chr "%9.0g"
 - attr(*, "label")= chr "Data file created by EpiData based on DEADALIVEHUSM2.REC"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># View the first few rows</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(data1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 49
  sex        race    doa        dod         time time2 status2   gcs   sbp   dbp
  &lt;dbl+lbl&gt;  &lt;dbl+l&gt; &lt;date&gt;     &lt;date&gt;     &lt;dbl&gt; &lt;dbl&gt; &lt;dbl+l&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1 2 [female] 1 [mal… 2011-01-01 2011-01-05     4     4 2 [dea…    15   150    87
2 1 [male]   1 [mal… 2011-01-03 2011-01-06     3     3 1 [ali…    15   152   108
3 2 [female] 1 [mal… 2011-01-06 2011-01-22    16    16 1 [ali…    15   231   117
4 2 [female] 1 [mal… 2011-01-16 2011-02-08    23    23 1 [ali…    11   110    79
5 1 [male]   1 [mal… 2011-01-18 2011-01-23     5     5 1 [ali…    15   199   134
6 2 [female] 2 [chi… 2011-01-20 2011-01-24     4     4 2 [dea…     7   190   101
# ℹ 39 more variables: hr &lt;dbl&gt;, dm &lt;dbl+lbl&gt;, hpt &lt;dbl+lbl&gt;, ckd &lt;dbl+lbl&gt;,
#   af &lt;dbl+lbl&gt;, hd &lt;dbl+lbl&gt;, dyslipid &lt;dbl+lbl&gt;, tia &lt;dbl+lbl&gt;,
#   smoker &lt;dbl+lbl&gt;, hb &lt;dbl&gt;, plat &lt;dbl&gt;, wbc &lt;dbl&gt;, na &lt;dbl&gt;, potas &lt;dbl&gt;,
#   gluc &lt;dbl&gt;, cbs &lt;dbl&gt;, chol &lt;dbl&gt;, tg &lt;dbl&gt;, urea &lt;dbl&gt;, referral &lt;dbl&gt;,
#   transport &lt;dbl&gt;, age2 &lt;dbl&gt;, sex2 &lt;dbl+lbl&gt;, marital2 &lt;dbl+lbl&gt;,
#   status1b &lt;dbl+lbl&gt;, status2b &lt;dbl+lbl&gt;, status3b &lt;dbl+lbl&gt;, hpt2 &lt;dbl+lbl&gt;,
#   marital3 &lt;dbl&gt;, race2 &lt;dbl+lbl&gt;, sex3 &lt;dbl+lbl&gt;, referral2 &lt;dbl&gt;, …</code></pre>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Quick summary</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(data1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      sex             race            doa                  dod            
 Min.   :1.000   Min.   :1.000   Min.   :2011-01-01   Min.   :2011-01-05  
 1st Qu.:1.000   1st Qu.:1.000   1st Qu.:2011-06-12   1st Qu.:2011-06-18  
 Median :2.000   Median :1.000   Median :2011-10-29   Median :2011-11-02  
 Mean   :1.571   Mean   :1.093   Mean   :2011-10-17   Mean   :2011-10-24  
 3rd Qu.:2.000   3rd Qu.:1.000   3rd Qu.:2012-03-11   3rd Qu.:2012-03-15  
 Max.   :2.000   Max.   :4.000   Max.   :2012-06-23   Max.   :2012-06-27  
                                                                          
      time            time2           status2           gcs       
 Min.   : 0.000   Min.   : 1.000   Min.   :1.000   Min.   : 3.00  
 1st Qu.: 2.250   1st Qu.: 2.250   1st Qu.:1.000   1st Qu.:10.00  
 Median : 4.000   Median : 4.000   Median :1.000   Median :15.00  
 Mean   : 6.469   Mean   : 6.491   Mean   :1.235   Mean   :12.44  
 3rd Qu.: 7.000   3rd Qu.: 7.000   3rd Qu.:1.000   3rd Qu.:15.00  
 Max.   :61.000   Max.   :61.000   Max.   :2.000   Max.   :15.00  
                                                   NA's   :1      
      sbp             dbp               hr               dm      
 Min.   : 75.0   Min.   : 42.00   Min.   : 37.00   Min.   :0.00  
 1st Qu.:143.0   1st Qu.: 79.00   1st Qu.: 68.00   1st Qu.:1.00  
 Median :161.0   Median : 91.00   Median : 80.00   Median :1.00  
 Mean   :163.1   Mean   : 91.88   Mean   : 82.67   Mean   :2.49  
 3rd Qu.:186.0   3rd Qu.:104.00   3rd Qu.: 95.00   3rd Qu.:2.00  
 Max.   :290.0   Max.   :160.00   Max.   :174.00   Max.   :8.00  
 NA's   :1       NA's   :1        NA's   :2        NA's   :71    
      hpt             ckd              af             hd           dyslipid    
 Min.   :0.000   Min.   :0.000   Min.   :0.00   Min.   :0.000   Min.   :0.000  
 1st Qu.:1.000   1st Qu.:2.000   1st Qu.:2.00   1st Qu.:1.000   1st Qu.:1.000  
 Median :1.000   Median :2.000   Median :2.00   Median :2.000   Median :2.000  
 Mean   :1.603   Mean   :4.128   Mean   :4.32   Mean   :3.444   Mean   :3.715  
 3rd Qu.:1.000   3rd Qu.:8.000   3rd Qu.:8.00   3rd Qu.:8.000   3rd Qu.:8.000  
 Max.   :8.000   Max.   :8.000   Max.   :8.00   Max.   :8.000   Max.   :8.000  
 NA's   :17      NA's   :117     NA's   :123    NA's   :100     NA's   :103    
      tia            smoker            hb             plat      
 Min.   :0.000   Min.   :0.000   Min.   : 5.30   Min.   : 43.0  
 1st Qu.:2.000   1st Qu.:1.000   1st Qu.:11.60   1st Qu.:185.8  
 Median :2.000   Median :2.000   Median :13.40   Median :235.0  
 Mean   :4.515   Mean   :3.441   Mean   :13.10   Mean   :236.3  
 3rd Qu.:8.000   3rd Qu.:8.000   3rd Qu.:14.62   3rd Qu.:275.8  
 Max.   :8.000   Max.   :8.000   Max.   :19.70   Max.   :459.0  
 NA's   :125     NA's   :115     NA's   :6       NA's   :6      
      wbc              na            potas           gluc       
 Min.   : 4.20   Min.   :109.0   Min.   :2.30   Min.   : 3.500  
 1st Qu.: 7.50   1st Qu.:136.0   1st Qu.:3.50   1st Qu.: 4.900  
 Median : 9.90   Median :138.0   Median :3.80   Median : 5.750  
 Mean   :10.46   Mean   :137.8   Mean   :3.86   Mean   : 7.369  
 3rd Qu.:12.70   3rd Qu.:140.0   3rd Qu.:4.20   3rd Qu.: 8.275  
 Max.   :27.00   Max.   :177.0   Max.   :5.70   Max.   :19.100  
 NA's   :6       NA's   :1       NA's   :1      NA's   :200     
      cbs              chol              tg             urea      
 Min.   : 2.400   Min.   : 2.600   Min.   :0.700   Min.   : 2.30  
 1st Qu.: 6.400   1st Qu.: 4.975   1st Qu.:0.900   1st Qu.: 4.80  
 Median : 8.100   Median : 6.050   Median :1.300   Median : 6.50  
 Mean   : 9.794   Mean   : 6.442   Mean   :1.585   Mean   : 7.87  
 3rd Qu.:12.100   3rd Qu.: 6.800   3rd Qu.:1.900   3rd Qu.: 9.00  
 Max.   :26.700   Max.   :19.600   Max.   :6.500   Max.   :41.00  
 NA's   :17       NA's   :186      NA's   :187     NA's   :1      
    referral       transport          age2            sex2      
 Min.   :1.000   Min.   :1.000   Min.   :20.00   Min.   :1.000  
 1st Qu.:3.000   1st Qu.:1.000   1st Qu.:52.00   1st Qu.:1.000  
 Median :4.000   Median :2.000   Median :61.00   Median :2.000  
 Mean   :3.199   Mean   :1.551   Mean   :60.82   Mean   :1.571  
 3rd Qu.:4.000   3rd Qu.:2.000   3rd Qu.:68.75   3rd Qu.:2.000  
 Max.   :4.000   Max.   :2.000   Max.   :94.00   Max.   :2.000  
 NA's   :10      NA's   :10                                     
    marital2        status1b        status2b        status3b     
 Min.   :1.000   Min.   :1.000   Min.   :1.000   Min.   :0.0000  
 1st Qu.:4.000   1st Qu.:1.000   1st Qu.:1.000   1st Qu.:0.0000  
 Median :4.000   Median :1.000   Median :1.000   Median :0.0000  
 Mean   :3.812   Mean   :1.235   Mean   :1.235   Mean   :0.2345  
 3rd Qu.:4.000   3rd Qu.:1.000   3rd Qu.:1.000   3rd Qu.:0.0000  
 Max.   :4.000   Max.   :2.000   Max.   :2.000   Max.   :1.0000  
 NA's   :3                                                       
      hpt2           marital3          race2             sex3       
 Min.   :0.0000   Min.   :0.0000   Min.   :0.0000   Min.   :0.0000  
 1st Qu.:0.2500   1st Qu.:1.0000   1st Qu.:1.0000   1st Qu.:0.0000  
 Median :1.0000   Median :1.0000   Median :1.0000   Median :0.0000  
 Mean   :0.7475   Mean   :0.9071   Mean   :0.9336   Mean   :0.4292  
 3rd Qu.:1.0000   3rd Qu.:1.0000   3rd Qu.:1.0000   3rd Qu.:1.0000  
 Max.   :1.0000   Max.   :1.0000   Max.   :1.0000   Max.   :1.0000  
 NA's   :28                                                         
   referral2      referral2cat      icd10cat        icd10cat2     
 Min.   :0.000   Min.   :0.000   Min.   :0.0000   Min.   :0.0000  
 1st Qu.:2.000   1st Qu.:0.000   1st Qu.:0.0000   1st Qu.:0.0000  
 Median :3.000   Median :1.000   Median :0.0000   Median :0.0000  
 Mean   :2.199   Mean   :0.615   Mean   :0.3761   Mean   :0.3407  
 3rd Qu.:3.000   3rd Qu.:1.000   3rd Qu.:1.0000   3rd Qu.:1.0000  
 Max.   :3.000   Max.   :1.000   Max.   :2.0000   Max.   :1.0000  
 NA's   :10                                                       
   icd10cat3          dm2cat          hpt2cat        dyslipid2cat   
 Min.   :0.0000   Min.   :0.0000   Min.   :0.0000   Min.   :0.0000  
 1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.:0.0000  
 Median :0.0000   Median :0.0000   Median :1.0000   Median :0.0000  
 Mean   :0.5973   Mean   :0.3274   Mean   :0.6549   Mean   :0.1195  
 3rd Qu.:2.0000   3rd Qu.:1.0000   3rd Qu.:1.0000   3rd Qu.:0.0000  
 Max.   :2.0000   Max.   :1.0000   Max.   :1.0000   Max.   :1.0000  
                                                                    </code></pre>
</div>
</div>
<p>The initial dataset comprised 226 observations with 49 variables related to sociodemographic, clinical, and laboratory information of stroke patients.</p>
<p>Upon exploration using the <code>str()</code> and <code>summary()</code> functions, several variables were identified to contain suspicious or non-informative coding (e.g., 8, 9) or even excessive missingness.</p>
</section>
<section id="visualising-the-problematic-data" class="level2">
<h2 class="anchored" data-anchor-id="visualising-the-problematic-data">Visualising the problematic data</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(naniar)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'naniar' was built under R version 4.4.3</code></pre>
</div>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Bar plot: Proportion of missing data by variable</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Naniar bar plot</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a><span class="fu">gg_miss_var</span>(data1) <span class="sc">+</span></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Proportion of Missing Data by Variable"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Final-Survival-Semiparametric_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>A bar chart using the <code>gg_miss_var()</code> function from the <code>naniar</code> package was employed to visualize the proportion of missing data by variable.</p>
<p>This revealed that several variables, particularly laboratory values like cholesterol and triglycerides, had high missingness (often &gt;80%).</p>
</section>
<section id="summarizing-the-problematic-data-for-decision" class="level2">
<h2 class="anchored" data-anchor-id="summarizing-the-problematic-data-for-decision">Summarizing the problematic data for decision</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># function for numerical data</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>summarize_data_quality <span class="ot">&lt;-</span> <span class="cf">function</span>(data, <span class="at">round_digits =</span> <span class="dv">2</span>) {</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="sc">!</span><span class="fu">requireNamespace</span>(<span class="st">"dplyr"</span>)) <span class="fu">install.packages</span>(<span class="st">"dplyr"</span>)</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="sc">!</span><span class="fu">requireNamespace</span>(<span class="st">"tidyr"</span>)) <span class="fu">install.packages</span>(<span class="st">"tidyr"</span>)</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">library</span>(dplyr)</span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">library</span>(tidyr)</span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Step 1: Missing count and percent</span></span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a>  missing_summary <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarise</span>(<span class="fu">across</span>(<span class="fu">everything</span>(), <span class="sc">~</span><span class="fu">sum</span>(<span class="fu">is.na</span>(.)))) <span class="sc">%&gt;%</span></span>
<span id="cb26-12"><a href="#cb26-12" aria-hidden="true" tabindex="-1"></a>    <span class="fu">pivot_longer</span>(<span class="at">cols =</span> <span class="fu">everything</span>(), <span class="at">names_to =</span> <span class="st">"Variable"</span>, <span class="at">values_to =</span> <span class="st">"Missing_Count"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb26-13"><a href="#cb26-13" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">Total =</span> <span class="fu">nrow</span>(data),</span>
<span id="cb26-14"><a href="#cb26-14" aria-hidden="true" tabindex="-1"></a>           <span class="at">Missing_Percent =</span> <span class="fu">round</span>((Missing_Count <span class="sc">/</span> Total) <span class="sc">*</span> <span class="dv">100</span>, round_digits))  <span class="co"># Rounded %</span></span>
<span id="cb26-15"><a href="#cb26-15" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb26-16"><a href="#cb26-16" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Step 2: Descriptive summary (numeric only)</span></span>
<span id="cb26-17"><a href="#cb26-17" aria-hidden="true" tabindex="-1"></a>  summary_stats <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb26-18"><a href="#cb26-18" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(<span class="fu">where</span>(is.numeric)) <span class="sc">%&gt;%</span></span>
<span id="cb26-19"><a href="#cb26-19" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarise</span>(<span class="fu">across</span>(<span class="fu">everything</span>(), <span class="fu">list</span>(</span>
<span id="cb26-20"><a href="#cb26-20" aria-hidden="true" tabindex="-1"></a>      <span class="at">count =</span> <span class="sc">~</span><span class="fu">sum</span>(<span class="sc">!</span><span class="fu">is.na</span>(.)),</span>
<span id="cb26-21"><a href="#cb26-21" aria-hidden="true" tabindex="-1"></a>      <span class="at">mean =</span> <span class="sc">~</span><span class="fu">round</span>(<span class="fu">mean</span>(., <span class="at">na.rm =</span> <span class="cn">TRUE</span>), round_digits),</span>
<span id="cb26-22"><a href="#cb26-22" aria-hidden="true" tabindex="-1"></a>      <span class="at">sd =</span> <span class="sc">~</span><span class="fu">round</span>(<span class="fu">sd</span>(., <span class="at">na.rm =</span> <span class="cn">TRUE</span>), round_digits),</span>
<span id="cb26-23"><a href="#cb26-23" aria-hidden="true" tabindex="-1"></a>      <span class="at">min =</span> <span class="sc">~</span><span class="fu">round</span>(<span class="fu">min</span>(., <span class="at">na.rm =</span> <span class="cn">TRUE</span>), round_digits),</span>
<span id="cb26-24"><a href="#cb26-24" aria-hidden="true" tabindex="-1"></a>      <span class="at">q25 =</span> <span class="sc">~</span><span class="fu">round</span>(<span class="fu">quantile</span>(., <span class="fl">0.25</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), round_digits),</span>
<span id="cb26-25"><a href="#cb26-25" aria-hidden="true" tabindex="-1"></a>      <span class="at">median =</span> <span class="sc">~</span><span class="fu">round</span>(<span class="fu">median</span>(., <span class="at">na.rm =</span> <span class="cn">TRUE</span>), round_digits),</span>
<span id="cb26-26"><a href="#cb26-26" aria-hidden="true" tabindex="-1"></a>      <span class="at">q75 =</span> <span class="sc">~</span><span class="fu">round</span>(<span class="fu">quantile</span>(., <span class="fl">0.75</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), round_digits),</span>
<span id="cb26-27"><a href="#cb26-27" aria-hidden="true" tabindex="-1"></a>      <span class="at">max =</span> <span class="sc">~</span><span class="fu">round</span>(<span class="fu">max</span>(., <span class="at">na.rm =</span> <span class="cn">TRUE</span>), round_digits)</span>
<span id="cb26-28"><a href="#cb26-28" aria-hidden="true" tabindex="-1"></a>    ), <span class="at">.names =</span> <span class="st">"{.col}_{.fn}"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb26-29"><a href="#cb26-29" aria-hidden="true" tabindex="-1"></a>    <span class="fu">pivot_longer</span>(<span class="at">cols =</span> <span class="fu">everything</span>(),</span>
<span id="cb26-30"><a href="#cb26-30" aria-hidden="true" tabindex="-1"></a>                 <span class="at">names_to =</span> <span class="fu">c</span>(<span class="st">"Variable"</span>, <span class="st">".value"</span>),</span>
<span id="cb26-31"><a href="#cb26-31" aria-hidden="true" tabindex="-1"></a>                 <span class="at">names_sep =</span> <span class="st">"_"</span>)</span>
<span id="cb26-32"><a href="#cb26-32" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb26-33"><a href="#cb26-33" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Step 3: Merge + final polish</span></span>
<span id="cb26-34"><a href="#cb26-34" aria-hidden="true" tabindex="-1"></a>  summary_table <span class="ot">&lt;-</span> <span class="fu">left_join</span>(missing_summary, summary_stats, <span class="at">by =</span> <span class="st">"Variable"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb26-35"><a href="#cb26-35" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(</span>
<span id="cb26-36"><a href="#cb26-36" aria-hidden="true" tabindex="-1"></a>      <span class="at">Action =</span> <span class="fu">case_when</span>(</span>
<span id="cb26-37"><a href="#cb26-37" aria-hidden="true" tabindex="-1"></a>        Missing_Percent <span class="sc">&gt;</span> <span class="dv">80</span> <span class="sc">~</span> <span class="st">"Drop (&gt;80% missing)"</span>,</span>
<span id="cb26-38"><a href="#cb26-38" aria-hidden="true" tabindex="-1"></a>        Missing_Percent <span class="sc">&gt;</span> <span class="dv">0</span> <span class="sc">~</span> <span class="st">"Consider imputing"</span>,</span>
<span id="cb26-39"><a href="#cb26-39" aria-hidden="true" tabindex="-1"></a>        <span class="cn">TRUE</span> <span class="sc">~</span> <span class="st">"Keep"</span></span>
<span id="cb26-40"><a href="#cb26-40" aria-hidden="true" tabindex="-1"></a>      ),</span>
<span id="cb26-41"><a href="#cb26-41" aria-hidden="true" tabindex="-1"></a>      <span class="at">MaxFlag =</span> <span class="fu">ifelse</span>(<span class="sc">!</span><span class="fu">is.na</span>(max) <span class="sc">&amp;</span> max <span class="sc">&gt;</span> <span class="dv">2</span>, <span class="st">"Check coding (&gt;2)"</span>, <span class="st">""</span>)</span>
<span id="cb26-42"><a href="#cb26-42" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">%&gt;%</span></span>
<span id="cb26-43"><a href="#cb26-43" aria-hidden="true" tabindex="-1"></a>    <span class="fu">arrange</span>(<span class="fu">desc</span>(Missing_Percent)) <span class="sc">%&gt;%</span></span>
<span id="cb26-44"><a href="#cb26-44" aria-hidden="true" tabindex="-1"></a>    <span class="fu">rename</span>(<span class="st">`</span><span class="at">Missing %</span><span class="st">`</span> <span class="ot">=</span> Missing_Percent)</span>
<span id="cb26-45"><a href="#cb26-45" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb26-46"><a href="#cb26-46" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(summary_table)</span>
<span id="cb26-47"><a href="#cb26-47" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb26-48"><a href="#cb26-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-49"><a href="#cb26-49" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-50"><a href="#cb26-50" aria-hidden="true" tabindex="-1"></a><span class="co"># function for categorical data</span></span>
<span id="cb26-51"><a href="#cb26-51" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-52"><a href="#cb26-52" aria-hidden="true" tabindex="-1"></a>view_categorical_labels <span class="ot">&lt;-</span> <span class="cf">function</span>(data) {</span>
<span id="cb26-53"><a href="#cb26-53" aria-hidden="true" tabindex="-1"></a>  cat_vars <span class="ot">&lt;-</span> <span class="fu">names</span>(data)[<span class="fu">sapply</span>(data, <span class="cf">function</span>(x) {</span>
<span id="cb26-54"><a href="#cb26-54" aria-hidden="true" tabindex="-1"></a>    <span class="fu">is.factor</span>(x) <span class="sc">||</span> <span class="fu">is.character</span>(x) <span class="sc">||</span> (<span class="st">"labels"</span> <span class="sc">%in%</span> <span class="fu">names</span>(<span class="fu">attributes</span>(x)))</span>
<span id="cb26-55"><a href="#cb26-55" aria-hidden="true" tabindex="-1"></a>  })]</span>
<span id="cb26-56"><a href="#cb26-56" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb26-57"><a href="#cb26-57" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> (var <span class="cf">in</span> cat_vars) {</span>
<span id="cb26-58"><a href="#cb26-58" aria-hidden="true" tabindex="-1"></a>    <span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">============================</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb26-59"><a href="#cb26-59" aria-hidden="true" tabindex="-1"></a>    <span class="fu">cat</span>(<span class="st">"📌 Variable:"</span>, var, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb26-60"><a href="#cb26-60" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb26-61"><a href="#cb26-61" aria-hidden="true" tabindex="-1"></a>    var_data <span class="ot">&lt;-</span> data[[var]]</span>
<span id="cb26-62"><a href="#cb26-62" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-63"><a href="#cb26-63" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Show value labels if exist</span></span>
<span id="cb26-64"><a href="#cb26-64" aria-hidden="true" tabindex="-1"></a>    label_attr <span class="ot">&lt;-</span> <span class="fu">attributes</span>(var_data)<span class="sc">$</span>labels</span>
<span id="cb26-65"><a href="#cb26-65" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> (<span class="sc">!</span><span class="fu">is.null</span>(label_attr)) {</span>
<span id="cb26-66"><a href="#cb26-66" aria-hidden="true" tabindex="-1"></a>      <span class="fu">cat</span>(<span class="st">"🔖 Value Labels:</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb26-67"><a href="#cb26-67" aria-hidden="true" tabindex="-1"></a>      <span class="fu">print</span>(label_attr)</span>
<span id="cb26-68"><a href="#cb26-68" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb26-69"><a href="#cb26-69" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb26-70"><a href="#cb26-70" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Show levels if factor or character</span></span>
<span id="cb26-71"><a href="#cb26-71" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> (<span class="fu">is.factor</span>(var_data) <span class="sc">||</span> <span class="fu">is.character</span>(var_data)) {</span>
<span id="cb26-72"><a href="#cb26-72" aria-hidden="true" tabindex="-1"></a>      <span class="fu">cat</span>(<span class="st">"📊 Levels / Unique Values:</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb26-73"><a href="#cb26-73" aria-hidden="true" tabindex="-1"></a>      <span class="fu">print</span>(<span class="fu">levels</span>(<span class="fu">as.factor</span>(var_data)))</span>
<span id="cb26-74"><a href="#cb26-74" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb26-75"><a href="#cb26-75" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-76"><a href="#cb26-76" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Frequency Table using as_factor for haven_labelled</span></span>
<span id="cb26-77"><a href="#cb26-77" aria-hidden="true" tabindex="-1"></a>    <span class="fu">cat</span>(<span class="st">"📈 Frequency Table:</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb26-78"><a href="#cb26-78" aria-hidden="true" tabindex="-1"></a>    freq_table <span class="ot">&lt;-</span> <span class="fu">table</span>(<span class="fu">as_factor</span>(var_data), <span class="at">useNA =</span> <span class="st">"ifany"</span>)</span>
<span id="cb26-79"><a href="#cb26-79" aria-hidden="true" tabindex="-1"></a>    <span class="fu">print</span>(freq_table)</span>
<span id="cb26-80"><a href="#cb26-80" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-81"><a href="#cb26-81" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Auto-check for suspicious codes</span></span>
<span id="cb26-82"><a href="#cb26-82" aria-hidden="true" tabindex="-1"></a>    suspicious_codes <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">8</span>, <span class="dv">9</span>, <span class="dv">88</span>, <span class="dv">99</span>, <span class="dv">888</span>, <span class="dv">999</span>, <span class="dv">8888</span>, <span class="dv">9999</span>)</span>
<span id="cb26-83"><a href="#cb26-83" aria-hidden="true" tabindex="-1"></a>    numeric_data <span class="ot">&lt;-</span> <span class="fu">suppressWarnings</span>(<span class="fu">as.numeric</span>(<span class="fu">as.character</span>(var_data)))</span>
<span id="cb26-84"><a href="#cb26-84" aria-hidden="true" tabindex="-1"></a>    invalids <span class="ot">&lt;-</span> <span class="fu">intersect</span>(suspicious_codes, <span class="fu">unique</span>(<span class="fu">na.omit</span>(numeric_data)))</span>
<span id="cb26-85"><a href="#cb26-85" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb26-86"><a href="#cb26-86" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> (<span class="fu">length</span>(invalids) <span class="sc">&gt;</span> <span class="dv">0</span>) {</span>
<span id="cb26-87"><a href="#cb26-87" aria-hidden="true" tabindex="-1"></a>      <span class="fu">cat</span>(<span class="st">"🚨 Warning: Suspicious codes detected -&gt; "</span>, <span class="fu">paste</span>(invalids, <span class="at">collapse =</span> <span class="st">", "</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb26-88"><a href="#cb26-88" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb26-89"><a href="#cb26-89" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb26-90"><a href="#cb26-90" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Summarize the dataset via the functions</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>summary_data1 <span class="ot">&lt;-</span> <span class="fu">summarize_data_quality</span>(data1)</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a><span class="co"># View it</span></span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(summary_data1)</span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a><span class="co"># categorical data</span></span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a><span class="fu">view_categorical_labels</span>(data1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
============================
📌 Variable: sex 
🔖 Value Labels:
  male female 
     1      2 
📈 Frequency Table:

  male female 
    97    129 

============================
📌 Variable: race 
🔖 Value Labels:
       malay      chinese      indians       others not recorded      missing 
           1            2            3            4            8            9 
📈 Frequency Table:

       malay      chinese      indians       others not recorded      missing 
         211           11            2            2            0            0 

============================
📌 Variable: status2 
🔖 Value Labels:
alive  dead 
    1     2 
📈 Frequency Table:

alive  dead 
  173    53 

============================
📌 Variable: dm 
🔖 Value Labels:
 no yes 
  0   1 
📈 Frequency Table:

  no  yes    2    8 &lt;NA&gt; 
   9   74   44   28   71 
🚨 Warning: Suspicious codes detected -&gt;  8 

============================
📌 Variable: hpt 
🔖 Value Labels:
 no yes 
  0   1 
📈 Frequency Table:

  no  yes    2    8 &lt;NA&gt; 
   2  157   37   13   17 
🚨 Warning: Suspicious codes detected -&gt;  8 

============================
📌 Variable: ckd 
🔖 Value Labels:
 no yes 
  0   1 
📈 Frequency Table:

  no  yes    2    8 &lt;NA&gt; 
  11   10   44   44  117 
🚨 Warning: Suspicious codes detected -&gt;  8 

============================
📌 Variable: af 
🔖 Value Labels:
 no yes 
  0   1 
📈 Frequency Table:

  no  yes    2    8 &lt;NA&gt; 
  10    5   44   44  123 
🚨 Warning: Suspicious codes detected -&gt;  8 

============================
📌 Variable: hd 
🔖 Value Labels:
 no yes 
  0   1 
📈 Frequency Table:

  no  yes    2    8 &lt;NA&gt; 
  11   30   46   39  100 
🚨 Warning: Suspicious codes detected -&gt;  8 

============================
📌 Variable: dyslipid 
🔖 Value Labels:
 no yes 
  0   1 
📈 Frequency Table:

  no  yes    2    8 &lt;NA&gt; 
  10   27   43   43  103 
🚨 Warning: Suspicious codes detected -&gt;  8 

============================
📌 Variable: tia 
🔖 Value Labels:
 no yes 
  0   1 
📈 Frequency Table:

  no  yes    2    8 &lt;NA&gt; 
  11    0   44   46  125 
🚨 Warning: Suspicious codes detected -&gt;  8 

============================
📌 Variable: smoker 
🔖 Value Labels:
 no yes 
  0   1 
📈 Frequency Table:

  no  yes    2    8 &lt;NA&gt; 
  11   22   44   34  115 
🚨 Warning: Suspicious codes detected -&gt;  8 

============================
📌 Variable: sex2 
🔖 Value Labels:
  male female 
     1      2 
📈 Frequency Table:

  male female 
    97    129 

============================
📌 Variable: marital2 
🔖 Value Labels:
 no yes 
  0   1 
📈 Frequency Table:

  no  yes    2    3    4 &lt;NA&gt; 
   0   10    1   10  202    3 

============================
📌 Variable: status1b 
🔖 Value Labels:
    alive      dead    others absconded 
        1         2         3         4 
📈 Frequency Table:

    alive      dead    others absconded 
      173        53         0         0 

============================
📌 Variable: status2b 
🔖 Value Labels:
alive  dead 
    1     2 
📈 Frequency Table:

alive  dead 
  173    53 

============================
📌 Variable: status3b 
🔖 Value Labels:
alive  dead 
    0     1 
📈 Frequency Table:

alive  dead 
  173    53 

============================
📌 Variable: hpt2 
🔖 Value Labels:
 no yes 
  0   1 
📈 Frequency Table:

  no  yes &lt;NA&gt; 
  50  148   28 

============================
📌 Variable: race2 
🔖 Value Labels:
 no yes 
  0   1 
📈 Frequency Table:

 no yes 
 15 211 

============================
📌 Variable: sex3 
🔖 Value Labels:
female   male 
     0      1 
📈 Frequency Table:

female   male 
   129     97 

============================
📌 Variable: referral2cat 
🔖 Value Labels:
       hospital GP/Home/Missing 
              0               1 
📈 Frequency Table:

       hospital GP/Home/Missing 
             87             139 

============================
📌 Variable: icd10cat 
🔖 Value Labels:
   CI,Others Haemorrhagic       Others 
           0            1            2 
📈 Frequency Table:

   CI,Others Haemorrhagic       Others 
         145           77            4 

============================
📌 Variable: icd10cat2 
🔖 Value Labels:
   CI,Others Haemorrhagic 
           0            1 
📈 Frequency Table:

   CI,Others Haemorrhagic 
         149           77 

============================
📌 Variable: icd10cat3 
🔖 Value Labels:
             CI,Others                    SAH ICB, Other Haemorrhage 
                     0                      1                      2 
📈 Frequency Table:

             CI,Others                    SAH ICB, Other Haemorrhage 
                   149                     19                     58 </code></pre>
</div>
</div>
<p>A structured summary of missingness and descriptive statistics was generated using custom functions. Categorical variables were inspected for value label inconsistencies, while numeric variables were assessed for completeness and distribution.</p>
<p>Several variables, such as <code>dm</code>, <code>hpt</code>, <code>ckd</code>, and <code>smoker</code>, contained suspicious codes (e.g., 8) representing non-standard or unknown values, which required recoding.</p>
<p>Based on this analysis, variables with high missingness or problematic coding were excluded from the final model.</p>
</section>
<section id="cleaning-the-problematic-dataset-for-analysis-select-variables-that-already-been-re-coded-appropriately" class="level2">
<h2 class="anchored" data-anchor-id="cleaning-the-problematic-dataset-for-analysis-select-variables-that-already-been-re-coded-appropriately">Cleaning the problematic dataset for analysis (select variables that already been re-coded appropriately)</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Create cleaned dataset</span></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>data2 <span class="ot">&lt;-</span> data1 <span class="sc">%&gt;%</span></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(</span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>    time2, status3b, age2, sex3, hpt2cat, dm2cat, dyslipid2cat,</span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>    referral2cat, icd10cat3</span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-10"><a href="#cb29-10" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(data2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 226
Columns: 9
$ time2        &lt;dbl&gt; 4, 3, 16, 23, 5, 4, 22, 14, 4, 2, 22, 2, 43, 2, 4, 4, 3, …
$ status3b     &lt;dbl+lbl&gt; 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,…
$ age2         &lt;dbl&gt; 69, 64, 63, 67, 66, 78, 55, 65, 67, 56, 50, 78, 59, 83, 8…
$ sex3         &lt;dbl+lbl&gt; 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1,…
$ hpt2cat      &lt;dbl&gt; 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, …
$ dm2cat       &lt;dbl&gt; 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, …
$ dyslipid2cat &lt;dbl&gt; 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
$ referral2cat &lt;dbl+lbl&gt; 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0,…
$ icd10cat3    &lt;dbl+lbl&gt; 0, 0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 1, 1,…</code></pre>
</div>
</div>
<p>A cleaned dataset (<code>data2</code>) was created by selecting only variables that had already been appropriately recoded.</p>
<p>The chosen variables were <code>time2</code>, <code>status3b</code> (event indicator), <code>age2</code>, <code>sex3</code>, <code>hpt2cat</code>, <code>dm2cat</code>, <code>dyslipid2cat</code>, <code>referral2cat</code>, and <code>icd10cat3</code>.</p>
<p>This step ensured the inclusion of well-defined, binary or categorical predictors and improved the quality and interpretability of the analysis.</p>
</section>
<section id="summarizing-and-visualising-the-cleaned-dataset" class="level2">
<h2 class="anchored" data-anchor-id="summarizing-and-visualising-the-cleaned-dataset">Summarizing and visualising the cleaned dataset</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Run the summarize function</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>summary_data2 <span class="ot">&lt;-</span> <span class="fu">summarize_data_quality</span>(data2)</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a><span class="co"># View it</span></span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(summary_data2)</span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a><span class="fu">view_categorical_labels</span>(data2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
============================
📌 Variable: status3b 
🔖 Value Labels:
alive  dead 
    0     1 
📈 Frequency Table:

alive  dead 
  173    53 

============================
📌 Variable: sex3 
🔖 Value Labels:
female   male 
     0      1 
📈 Frequency Table:

female   male 
   129     97 

============================
📌 Variable: referral2cat 
🔖 Value Labels:
       hospital GP/Home/Missing 
              0               1 
📈 Frequency Table:

       hospital GP/Home/Missing 
             87             139 

============================
📌 Variable: icd10cat3 
🔖 Value Labels:
             CI,Others                    SAH ICB, Other Haemorrhage 
                     0                      1                      2 
📈 Frequency Table:

             CI,Others                    SAH ICB, Other Haemorrhage 
                   149                     19                     58 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(forcats)</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Barplot : status3b</span></span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>data2 <span class="sc">%&gt;%</span></span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">status3b =</span> <span class="fu">case_when</span>(</span>
<span id="cb33-10"><a href="#cb33-10" aria-hidden="true" tabindex="-1"></a>      status3b <span class="sc">==</span> <span class="dv">0</span> <span class="sc">~</span> <span class="st">"Alive"</span>,</span>
<span id="cb33-11"><a href="#cb33-11" aria-hidden="true" tabindex="-1"></a>      status3b <span class="sc">==</span> <span class="dv">1</span> <span class="sc">~</span> <span class="st">"Dead"</span>,</span>
<span id="cb33-12"><a href="#cb33-12" aria-hidden="true" tabindex="-1"></a>      <span class="cn">TRUE</span> <span class="sc">~</span> <span class="cn">NA_character_</span></span>
<span id="cb33-13"><a href="#cb33-13" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb33-14"><a href="#cb33-14" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb33-15"><a href="#cb33-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> status3b, <span class="at">fill =</span> status3b)) <span class="sc">+</span></span>
<span id="cb33-16"><a href="#cb33-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>() <span class="sc">+</span></span>
<span id="cb33-17"><a href="#cb33-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Distribution of Survival Status"</span>,</span>
<span id="cb33-18"><a href="#cb33-18" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Status at Discharge"</span>, <span class="at">y =</span> <span class="st">"Count"</span>) <span class="sc">+</span></span>
<span id="cb33-19"><a href="#cb33-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb33-20"><a href="#cb33-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"Alive"</span> <span class="ot">=</span> <span class="st">"#4CAF50"</span>, <span class="st">"Dead"</span> <span class="ot">=</span> <span class="st">"#F44336"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Final-Survival-Semiparametric_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Barplot : sex</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>data2 <span class="sc">%&gt;%</span></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">sex3 =</span> <span class="fu">factor</span>(sex3, <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Female"</span>, <span class="st">"Male"</span>))) <span class="sc">%&gt;%</span></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> sex3, <span class="at">fill =</span> sex3)) <span class="sc">+</span></span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>() <span class="sc">+</span></span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Sex Distribution"</span>, <span class="at">x =</span> <span class="st">"Sex"</span>, <span class="at">y =</span> <span class="st">"Count"</span>) <span class="sc">+</span></span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb34-9"><a href="#cb34-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"#FF69B4"</span>, <span class="st">"#2196F3"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Final-Survival-Semiparametric_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Barplot : icd10cat3</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>data2 <span class="sc">%&gt;%</span></span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">icd10cat3 =</span> <span class="fu">factor</span>(icd10cat3,</span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>                            <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">2</span>),</span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>                            <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Cerebral Ischaemia"</span>, <span class="st">"SAH"</span>, <span class="st">"ICB/Others"</span>))) <span class="sc">%&gt;%</span></span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> icd10cat3, <span class="at">fill =</span> icd10cat3)) <span class="sc">+</span></span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>() <span class="sc">+</span></span>
<span id="cb35-9"><a href="#cb35-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Stroke Subtype Distribution"</span>, <span class="at">x =</span> <span class="st">"Stroke Type"</span>, <span class="at">y =</span> <span class="st">"Count"</span>) <span class="sc">+</span></span>
<span id="cb35-10"><a href="#cb35-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb35-11"><a href="#cb35-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_brewer</span>(<span class="at">palette =</span> <span class="st">"Set2"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Final-Survival-Semiparametric_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Barplot : referral2cat</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>data2 <span class="sc">%&gt;%</span></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">referral2cat =</span> <span class="fu">factor</span>(referral2cat,</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>                               <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>),</span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>                               <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Hospital"</span>, <span class="st">"GP/Home/Missing"</span>))) <span class="sc">%&gt;%</span></span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> referral2cat, <span class="at">fill =</span> referral2cat)) <span class="sc">+</span></span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>() <span class="sc">+</span></span>
<span id="cb36-9"><a href="#cb36-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Referral Source"</span>, <span class="at">x =</span> <span class="st">"Referral Category"</span>, <span class="at">y =</span> <span class="st">"Count"</span>) <span class="sc">+</span></span>
<span id="cb36-10"><a href="#cb36-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb36-11"><a href="#cb36-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"#03A9F4"</span>, <span class="st">"#FFC107"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Final-Survival-Semiparametric_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Descriptive statistics and frequency tables were produced for the cleaned dataset.</p>
<p>Among the 226 patients, 53 deaths were observed (23.5%). The majority were females (57.1%) and had cerebral ischaemic stroke. Most referrals originated from home or private clinics (61.5%).</p>
<p>These characteristics provided an overview of the study population before proceeding with model fitting.</p>
</section>
<section id="convert-the-cleaned-data-to-appropriate-types" class="level2">
<h2 class="anchored" data-anchor-id="convert-the-cleaned-data-to-appropriate-types">Convert the cleaned data to appropriate types</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>data3 <span class="ot">&lt;-</span> data2 <span class="sc">%&gt;%</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">status3b =</span> <span class="fu">as.numeric</span>(<span class="fu">zap_labels</span>(status3b)), </span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">sex3 =</span> <span class="fu">as.factor</span>(sex3),</span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">hpt2cat =</span> <span class="fu">as.factor</span>(hpt2cat),</span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">dm2cat =</span> <span class="fu">as.factor</span>(dm2cat),</span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">dyslipid2cat =</span> <span class="fu">as.factor</span>(dyslipid2cat),</span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">referral2cat =</span> <span class="fu">as.factor</span>(referral2cat),</span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">icd10cat3 =</span> <span class="fu">as.factor</span>(icd10cat3)</span>
<span id="cb37-10"><a href="#cb37-10" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Prior to modeling, variables were converted to appropriate types.</p>
<p>Categorical variables were converted to factors and the outcome variable (status3b) was transformed into a numeric binary indicator (0 = alive, 1 = dead). This is essential for ensuring compatibility with the Cox proportional hazards model.</p>
</section>
<section id="create-survival-object" class="level2">
<h2 class="anchored" data-anchor-id="create-survival-object">Create Survival Object</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>surv_obj <span class="ot">&lt;-</span> <span class="fu">Surv</span>(<span class="at">time =</span> data3<span class="sc">$</span>time2, <span class="at">event =</span> data3<span class="sc">$</span>status3b)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>A survival object was created using the <code>Surv()</code> function, which combines the time-to-event (<code>time2</code>) and event status (<code>status3b</code>) variables.</p>
<p>This served as the basis for fitting the semiparametric Cox model and for plotting survival curves.</p>
</section>
<section id="fit-cox-proportional-hazard-model-semi-parametic" class="level2">
<h2 class="anchored" data-anchor-id="fit-cox-proportional-hazard-model-semi-parametic">Fit Cox Proportional Hazard Model (Semi-parametic)</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>cox_model <span class="ot">&lt;-</span> <span class="fu">coxph</span>(surv_obj <span class="sc">~</span> age2 <span class="sc">+</span> sex3 <span class="sc">+</span> hpt2cat <span class="sc">+</span> dm2cat <span class="sc">+</span> dyslipid2cat <span class="sc">+</span> referral2cat <span class="sc">+</span> icd10cat3, <span class="at">data =</span> data3)</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(cox_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
coxph(formula = surv_obj ~ age2 + sex3 + hpt2cat + dm2cat + dyslipid2cat + 
    referral2cat + icd10cat3, data = data3)

  n= 226, number of events= 53 

                   coef exp(coef)  se(coef)      z Pr(&gt;|z|)  
age2           0.027613  1.027997  0.011472  2.407   0.0161 *
sex31         -0.414739  0.660513  0.311745 -1.330   0.1834  
hpt2cat1       0.009096  1.009138  0.321861  0.028   0.9775  
dm2cat1       -0.215164  0.806409  0.346710 -0.621   0.5349  
dyslipid2cat1 -1.146113  0.317870  1.030351 -1.112   0.2660  
referral2cat1 -0.146637  0.863607  0.331885 -0.442   0.6586  
icd10cat31     0.757801  2.133578  0.434232  1.745   0.0810 .
icd10cat32     0.724670  2.064050  0.372580  1.945   0.0518 .
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

              exp(coef) exp(-coef) lower .95 upper .95
age2             1.0280     0.9728   1.00514     1.051
sex31            0.6605     1.5140   0.35853     1.217
hpt2cat1         1.0091     0.9909   0.53701     1.896
dm2cat1          0.8064     1.2401   0.40873     1.591
dyslipid2cat1    0.3179     3.1459   0.04219     2.395
referral2cat1    0.8636     1.1579   0.45063     1.655
icd10cat31       2.1336     0.4687   0.91094     4.997
icd10cat32       2.0641     0.4845   0.99444     4.284

Concordance= 0.739  (se = 0.039 )
Likelihood ratio test= 18.42  on 8 df,   p=0.02
Wald test            = 16.87  on 8 df,   p=0.03
Score (logrank) test = 17.6  on 8 df,   p=0.02</code></pre>
</div>
</div>
<p>The Cox proportional hazards model was fitted using the cleaned dataset (data3). The following interpretations are based on the model output:</p>
<ul>
<li><p><strong>Age</strong> was significantly associated with increased hazard of death (HR = 1.028; 95% CI: 1.005–1.051; <em>p</em> = 0.016), indicating that each additional year of age raised the hazard by approximately 2.8%.</p></li>
<li><p><strong>Stroke subtype (icd10cat3)</strong> showed borderline significant results. Patients with subarachnoid hemorrhage (SAH) or intracerebral bleeding had approximately twice the hazard of death compared to those with cerebral ischemia or other types:</p></li>
<li><p>SAH (HR = 2.13; 95% CI: 0.91–5.00; <em>p</em> = 0.081)</p></li>
<li><p>ICB/Others (HR = 2.06; 95% CI: 0.99–4.28; <em>p</em> = 0.052)</p></li>
</ul>
<!-- -->
<ul>
<li><p>Other variables such as <strong>sex</strong>, <strong>hypertension</strong>, <strong>diabetes</strong>, <strong>dyslipidemia</strong>, and <strong>referral source</strong> did not show statistically significant associations with survival.</p></li>
<li><p>Overall, the model demonstrated acceptable discrimination (concordance index = 0.739), and global tests (Likelihood Ratio, Wald, and Score) were statistically significant, indicating a good model fit.</p></li>
</ul>
</section>
<section id="check-proportional-hazard-assumption" class="level2">
<h2 class="anchored" data-anchor-id="check-proportional-hazard-assumption">Check Proportional Hazard Assumption</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cox.zph</span>(cox_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>               chisq df      p
age2          1.7696  1 0.1834
sex3          0.0169  1 0.8965
hpt2cat       0.1625  1 0.6869
dm2cat        4.6347  1 0.0313
dyslipid2cat  0.7003  1 0.4027
referral2cat  8.2320  1 0.0041
icd10cat3     9.5670  2 0.0084
GLOBAL       15.4725  8 0.0506</code></pre>
</div>
</div>
<ul>
<li><p>Variables such as <strong>diabetes (dm2cat)</strong> (<em>p</em> = 0.031), <strong>referral source (referral2cat)</strong> (<em>p</em> = 0.004), and <strong>stroke type (icd10cat3)</strong> (<em>p</em> = 0.008) violated the assumption, suggesting that their effects on the hazard of death may vary over time. Need to be addressed in further advance modelling.</p></li>
<li><p>The <strong>global test</strong> was borderline significant (<em>p</em> = 0.0506), further supporting the need to consider alternative modeling strategies such as stratification or time-varying covariates for those variables.</p></li>
</ul>
</section>
<section id="plot-survival-curves-by-sex" class="level2">
<h2 class="anchored" data-anchor-id="plot-survival-curves-by-sex">Plot survival curves by Sex</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggsurvplot</span>(</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">survfit</span>(surv_obj <span class="sc">~</span> sex3, <span class="at">data =</span> data3),</span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> data3,</span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">pval =</span> <span class="cn">TRUE</span>,</span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">conf.int =</span> <span class="cn">TRUE</span>,</span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">risk.table =</span> <span class="cn">TRUE</span>,</span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">legend.labs =</span> <span class="fu">c</span>(<span class="st">"Male"</span>, <span class="st">"Female"</span>)</span>
<span id="cb43-8"><a href="#cb43-8" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Final-Survival-Semiparametric_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Kaplan-Meier survival curves were plotted by sex.</p>
<p>Although males appeared to have slightly better survival, the log-rank test indicated that the difference was not statistically significant (<em>p</em> = 0.17).</p>
<p>This visual representation complements the Cox model finding, which also did not show a significant effect of sex on survival outcome.</p>
</section>
<section id="predict-survival-for-a-hypothetical-patient" class="level2">
<h2 class="anchored" data-anchor-id="predict-survival-for-a-hypothetical-patient">Predict Survival for a Hypothetical Patient</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(survival)</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(survminer)</span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>predict_survival_plot <span class="ot">&lt;-</span> <span class="cf">function</span>(model, data, patient_profile, <span class="at">conf.int =</span> <span class="cn">TRUE</span>, <span class="at">title =</span> <span class="st">"Predicted Survival Curve"</span>) {</span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Ensure all factor variables are matched to model's data</span></span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a>  vars <span class="ot">&lt;-</span> <span class="fu">names</span>(patient_profile)</span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-8"><a href="#cb44-8" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> (var <span class="cf">in</span> vars) {</span>
<span id="cb44-9"><a href="#cb44-9" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> (<span class="fu">is.factor</span>(data[[var]])) {</span>
<span id="cb44-10"><a href="#cb44-10" aria-hidden="true" tabindex="-1"></a>      patient_profile[[var]] <span class="ot">&lt;-</span> <span class="fu">factor</span>(patient_profile[[var]], <span class="at">levels =</span> <span class="fu">levels</span>(data[[var]]))</span>
<span id="cb44-11"><a href="#cb44-11" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb44-12"><a href="#cb44-12" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb44-13"><a href="#cb44-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-14"><a href="#cb44-14" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Predict survival</span></span>
<span id="cb44-15"><a href="#cb44-15" aria-hidden="true" tabindex="-1"></a>  surv_pred <span class="ot">&lt;-</span> <span class="fu">survfit</span>(model, <span class="at">newdata =</span> patient_profile)</span>
<span id="cb44-16"><a href="#cb44-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-17"><a href="#cb44-17" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Plot survival curve</span></span>
<span id="cb44-18"><a href="#cb44-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggsurvplot</span>(</span>
<span id="cb44-19"><a href="#cb44-19" aria-hidden="true" tabindex="-1"></a>    surv_pred,</span>
<span id="cb44-20"><a href="#cb44-20" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> patient_profile,</span>
<span id="cb44-21"><a href="#cb44-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">conf.int =</span> conf.int,</span>
<span id="cb44-22"><a href="#cb44-22" aria-hidden="true" tabindex="-1"></a>    <span class="at">legend.title =</span> <span class="st">"Hypothetical Patient"</span>,</span>
<span id="cb44-23"><a href="#cb44-23" aria-hidden="true" tabindex="-1"></a>    <span class="at">ggtheme =</span> <span class="fu">theme_minimal</span>(),</span>
<span id="cb44-24"><a href="#cb44-24" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> title</span>
<span id="cb44-25"><a href="#cb44-25" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb44-26"><a href="#cb44-26" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create patient profile</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>my_patient <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">age2 =</span> <span class="dv">65</span>,</span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">sex3 =</span> <span class="st">"1"</span>,</span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">hpt2cat =</span> <span class="st">"1"</span>,</span>
<span id="cb45-6"><a href="#cb45-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">dm2cat =</span> <span class="st">"1"</span>,</span>
<span id="cb45-7"><a href="#cb45-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">dyslipid2cat =</span> <span class="st">"0"</span>,</span>
<span id="cb45-8"><a href="#cb45-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">referral2cat =</span> <span class="st">"1"</span>,</span>
<span id="cb45-9"><a href="#cb45-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">icd10cat3 =</span> <span class="st">"1"</span></span>
<span id="cb45-10"><a href="#cb45-10" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb45-11"><a href="#cb45-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-12"><a href="#cb45-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Call the function</span></span>
<span id="cb45-13"><a href="#cb45-13" aria-hidden="true" tabindex="-1"></a><span class="fu">predict_survival_plot</span>(cox_model, data3, my_patient, <span class="at">conf.int =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Final-Survival-Semiparametric_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>A personalized survival curve was generated for a hypothetical patient: a <strong>65-year-old male</strong> diagnosed with <strong>subarachnoid hemorrhage (SAH)</strong>, with a history of <strong>hypertension and diabetes</strong>, no dyslipidemia, and referred from <strong>home or a private clinic</strong>. This profile was chosen to reflect a higher-risk stroke case within the dataset.</p>
<p>Based on the fitted Cox proportional hazards model, the predicted survival probabilities over time were estimated as follows:</p>
<p>Day 5: <strong>92%</strong></p>
<p>Day 10: <strong>85%</strong></p>
<p>Day 15: <strong>76%</strong></p>
<p>Day 20: <strong>65%</strong></p>
<p>Day 30: <strong>48%</strong></p>
<p>Day 45: <strong>30%</strong></p>
<p>Day 60: <strong>15%</strong></p>
<p>These estimates indicate a gradual decline in survival probability over time, with a particularly steep drop beyond day 20. By day 30, the patient’s survival probability is already below 50%, highlighting the urgency of clinical attention in such cases.</p>
<p>Hence, the establishment of this surival semiparametric model enables <strong>individualized prognostic insights</strong> tailored to a patient’s profile, which can supports <strong>clinical decision-making</strong> and priority setting, especially for follow-up care or palliative discussions. Besides, it also can enhances <strong>patient–clinician communication</strong> by providing quantifiable risk trajectories. In conclusion, it can provide a valuable tool for <strong>evidence-based, patient-centered care</strong> in stroke management itself.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>