<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.39">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Multinomial Outcomes</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="multinomial_files/libs/clipboard/clipboard.min.js"></script>
<script src="multinomial_files/libs/quarto-html/quarto.js"></script>
<script src="multinomial_files/libs/quarto-html/popper.min.js"></script>
<script src="multinomial_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="multinomial_files/libs/quarto-html/anchor.min.js"></script>
<link href="multinomial_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="multinomial_files/libs/quarto-html/quarto-syntax-highlighting-e26003cea8cd680ca0c55a263523d882.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="multinomial_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="multinomial_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="multinomial_files/libs/bootstrap/bootstrap-737211cf3a38c443be353d65ddf28aed.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="multinomial_files/libs/kePrint-0.0.1/kePrint.js"></script>

<link href="multinomial_files/libs/lightable-0.0.1/lightable.css" rel="stylesheet">



</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article toc-left">
<div id="quarto-sidebar-toc-left" class="sidebar toc-left">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul class="collapse">
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"><span class="header-section-number">1</span> Introduction</a></li>
  <li><a href="#load-packages" id="toc-load-packages" class="nav-link" data-scroll-target="#load-packages"><span class="header-section-number">2</span> Load packages</a>
  <ul class="collapse">
  <li><a href="#general-packages" id="toc-general-packages" class="nav-link" data-scroll-target="#general-packages"><span class="header-section-number">2.1</span> General packages</a></li>
  </ul></li>
  <li><a href="#about-the-dataset" id="toc-about-the-dataset" class="nav-link" data-scroll-target="#about-the-dataset"><span class="header-section-number">3</span> About the dataset</a></li>
  <li><a href="#load-the-dataset" id="toc-load-the-dataset" class="nav-link" data-scroll-target="#load-the-dataset"><span class="header-section-number">4</span> Load the dataset</a></li>
  <li><a href="#data-wrangling" id="toc-data-wrangling" class="nav-link" data-scroll-target="#data-wrangling"><span class="header-section-number">5</span> Data wrangling</a></li>
  <li><a href="#exploratory-data-analysis" id="toc-exploratory-data-analysis" class="nav-link" data-scroll-target="#exploratory-data-analysis"><span class="header-section-number">6</span> Exploratory Data Analysis</a>
  <ul class="collapse">
  <li><a href="#handling-missing-data" id="toc-handling-missing-data" class="nav-link" data-scroll-target="#handling-missing-data"><span class="header-section-number">6.1</span> Handling missing data</a></li>
  <li><a href="#categorize-fbs-into-3-levels" id="toc-categorize-fbs-into-3-levels" class="nav-link" data-scroll-target="#categorize-fbs-into-3-levels"><span class="header-section-number">6.2</span> Categorize fbs into 3 levels</a></li>
  <li><a href="#checking-level-of-cat_fbs" id="toc-checking-level-of-cat_fbs" class="nav-link" data-scroll-target="#checking-level-of-cat_fbs"><span class="header-section-number">6.3</span> Checking level of cat_fbs</a></li>
  <li><a href="#re-level-for-cat_fbs" id="toc-re-level-for-cat_fbs" class="nav-link" data-scroll-target="#re-level-for-cat_fbs"><span class="header-section-number">6.4</span> Re-level for cat_fbs</a></li>
  </ul></li>
  <li><a href="#multinomial-analysis-using-vgam-packages" id="toc-multinomial-analysis-using-vgam-packages" class="nav-link" data-scroll-target="#multinomial-analysis-using-vgam-packages"><span class="header-section-number">7</span> Multinomial analysis using VGAM packages</a>
  <ul class="collapse">
  <li><a href="#model-with-univariable" id="toc-model-with-univariable" class="nav-link" data-scroll-target="#model-with-univariable"><span class="header-section-number">7.1</span> Model with univariable</a></li>
  <li><a href="#multivariate-model-analysis" id="toc-multivariate-model-analysis" class="nav-link" data-scroll-target="#multivariate-model-analysis"><span class="header-section-number">7.2</span> Multivariate Model Analysis</a></li>
  </ul></li>
  <li><a href="#multinomial-analysis-using-nnet-package" id="toc-multinomial-analysis-using-nnet-package" class="nav-link" data-scroll-target="#multinomial-analysis-using-nnet-package"><span class="header-section-number">8</span> Multinomial analysis using NNET package</a>
  <ul class="collapse">
  <li><a href="#load-the-packages" id="toc-load-the-packages" class="nav-link" data-scroll-target="#load-the-packages"><span class="header-section-number">8.1</span> Load the packages</a></li>
  <li><a href="#univariate-model" id="toc-univariate-model" class="nav-link" data-scroll-target="#univariate-model"><span class="header-section-number">8.2</span> Univariate model</a></li>
  <li><a href="#comparing-vgamvglm-and-nnetmultinom" id="toc-comparing-vgamvglm-and-nnetmultinom" class="nav-link" data-scroll-target="#comparing-vgamvglm-and-nnetmultinom"><span class="header-section-number">8.3</span> Comparing VGAM::vglm and nnet::multinom</a></li>
  </ul></li>
  <li><a href="#inferences" id="toc-inferences" class="nav-link" data-scroll-target="#inferences"><span class="header-section-number">9</span> Inferences</a>
  <ul class="collapse">
  <li><a href="#using-vgam" id="toc-using-vgam" class="nav-link" data-scroll-target="#using-vgam"><span class="header-section-number">9.1</span> Using VGAM</a></li>
  <li><a href="#using-nnet-packages" id="toc-using-nnet-packages" class="nav-link" data-scroll-target="#using-nnet-packages"><span class="header-section-number">9.2</span> Using NNET packages</a></li>
  <li><a href="#getting-p-value-and-ci-from-nnetmultinom" id="toc-getting-p-value-and-ci-from-nnetmultinom" class="nav-link" data-scroll-target="#getting-p-value-and-ci-from-nnetmultinom"><span class="header-section-number">9.3</span> Getting p-value and CI from nnet::multinom</a></li>
  <li><a href="#ci-for-nnetmultinom" id="toc-ci-for-nnetmultinom" class="nav-link" data-scroll-target="#ci-for-nnetmultinom"><span class="header-section-number">9.4</span> CI for nnet::multinom</a></li>
  </ul></li>
  <li><a href="#prediction" id="toc-prediction" class="nav-link" data-scroll-target="#prediction"><span class="header-section-number">10</span> Prediction</a>
  <ul class="collapse">
  <li><a href="#predict-the-log-odds" id="toc-predict-the-log-odds" class="nav-link" data-scroll-target="#predict-the-log-odds"><span class="header-section-number">10.1</span> Predict the log odds</a></li>
  <li><a href="#predict-the-probability" id="toc-predict-the-probability" class="nav-link" data-scroll-target="#predict-the-probability"><span class="header-section-number">10.2</span> Predict the probability</a></li>
  </ul></li>
  </ul>
</nav>
</div>
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Multinomial Outcomes</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>

<nav id="TOC-body" role="doc-toc">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction"><span class="header-section-number">1</span> Introduction</a></li>
  <li><a href="#load-packages" id="toc-load-packages"><span class="header-section-number">2</span> Load packages</a>
  <ul>
  <li><a href="#general-packages" id="toc-general-packages"><span class="header-section-number">2.1</span> General packages</a></li>
  </ul></li>
  <li><a href="#about-the-dataset" id="toc-about-the-dataset"><span class="header-section-number">3</span> About the dataset</a></li>
  <li><a href="#load-the-dataset" id="toc-load-the-dataset"><span class="header-section-number">4</span> Load the dataset</a></li>
  <li><a href="#data-wrangling" id="toc-data-wrangling"><span class="header-section-number">5</span> Data wrangling</a></li>
  <li><a href="#exploratory-data-analysis" id="toc-exploratory-data-analysis"><span class="header-section-number">6</span> Exploratory Data Analysis</a>
  <ul>
  <li><a href="#handling-missing-data" id="toc-handling-missing-data"><span class="header-section-number">6.1</span> Handling missing data</a></li>
  <li><a href="#categorize-fbs-into-3-levels" id="toc-categorize-fbs-into-3-levels"><span class="header-section-number">6.2</span> Categorize fbs into 3 levels</a></li>
  <li><a href="#checking-level-of-cat_fbs" id="toc-checking-level-of-cat_fbs"><span class="header-section-number">6.3</span> Checking level of cat_fbs</a></li>
  <li><a href="#re-level-for-cat_fbs" id="toc-re-level-for-cat_fbs"><span class="header-section-number">6.4</span> Re-level for cat_fbs</a></li>
  </ul></li>
  <li><a href="#multinomial-analysis-using-vgam-packages" id="toc-multinomial-analysis-using-vgam-packages"><span class="header-section-number">7</span> Multinomial analysis using VGAM packages</a>
  <ul>
  <li><a href="#model-with-univariable" id="toc-model-with-univariable"><span class="header-section-number">7.1</span> Model with univariable</a></li>
  <li><a href="#multivariate-model-analysis" id="toc-multivariate-model-analysis"><span class="header-section-number">7.2</span> Multivariate Model Analysis</a></li>
  </ul></li>
  <li><a href="#multinomial-analysis-using-nnet-package" id="toc-multinomial-analysis-using-nnet-package"><span class="header-section-number">8</span> Multinomial analysis using NNET package</a>
  <ul>
  <li><a href="#load-the-packages" id="toc-load-the-packages"><span class="header-section-number">8.1</span> Load the packages</a></li>
  <li><a href="#univariate-model" id="toc-univariate-model"><span class="header-section-number">8.2</span> Univariate model</a></li>
  <li><a href="#comparing-vgamvglm-and-nnetmultinom" id="toc-comparing-vgamvglm-and-nnetmultinom"><span class="header-section-number">8.3</span> Comparing VGAM::vglm and nnet::multinom</a></li>
  </ul></li>
  <li><a href="#inferences" id="toc-inferences"><span class="header-section-number">9</span> Inferences</a>
  <ul>
  <li><a href="#using-vgam" id="toc-using-vgam"><span class="header-section-number">9.1</span> Using VGAM</a></li>
  <li><a href="#using-nnet-packages" id="toc-using-nnet-packages"><span class="header-section-number">9.2</span> Using NNET packages</a></li>
  <li><a href="#getting-p-value-and-ci-from-nnetmultinom" id="toc-getting-p-value-and-ci-from-nnetmultinom"><span class="header-section-number">9.3</span> Getting p-value and CI from nnet::multinom</a></li>
  <li><a href="#ci-for-nnetmultinom" id="toc-ci-for-nnetmultinom"><span class="header-section-number">9.4</span> CI for nnet::multinom</a></li>
  </ul></li>
  <li><a href="#prediction" id="toc-prediction"><span class="header-section-number">10</span> Prediction</a>
  <ul>
  <li><a href="#predict-the-log-odds" id="toc-predict-the-log-odds"><span class="header-section-number">10.1</span> Predict the log odds</a></li>
  <li><a href="#predict-the-probability" id="toc-predict-the-probability"><span class="header-section-number">10.2</span> Predict the probability</a></li>
  </ul></li>
  </ul>
</nav>
<p><img src="members.png" style="border-radius: 15px; display: block; margin: auto;" width="400px"></p>
<section id="introduction" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Introduction</h1>
<p>Multinomial logistic regression is a statistical method used to model relationships between a polytomous (i.e., having more than two categories) nominal outcome variable and one or more independent variables. Unlike binary logistic regression, which is limited to dichotomous outcomes, multinomial logistic regression accommodates outcome variables with three or more unordered categories. This method estimates the probability of each category relative to a reference group by fitting a series of binary logistic regressions, producing a set of coefficients that reflect the log-odds of membership in each non-reference category. It is particularly useful in public health and epidemiological research where outcomes such as disease classification, behavioral responses, or clinical stages are categorized without a natural ordering. The model can incorporate both continuous and categorical predictors, enabling comprehensive analysis of complex associations within population health datasets.</p>
</section>
<section id="load-packages" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Load packages</h1>
<section id="general-packages" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="general-packages"><span class="header-section-number">2.1</span> General packages</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'ggplot2' was built under R version 4.4.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'purrr' was built under R version 4.4.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'lubridate' was built under R version 4.4.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.1     ✔ tibble    3.2.1
✔ lubridate 1.9.4     ✔ tidyr     1.3.1
✔ purrr     1.0.4     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gtsummary)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'gtsummary' was built under R version 4.4.3</code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(kableExtra)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'kableExtra' was built under R version 4.4.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'kableExtra'

The following object is masked from 'package:dplyr':

    group_rows</code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(haven)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="about-the-dataset" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> About the dataset</h1>
<p>This dataset derived from a health or metabolic syndrome screening study. It includes anthropometric, biochemical, and lifestyle variables. The primary outcome of interest for your analysis is fasting blood sugar (fbs). The dataset consist of the following variables;</p>
<ul>
<li>codesub: Participant code or ID.</li>
<li>age: Age in years (numeric).</li>
<li>hpt: Hypertension status — “yes” or “no”.</li>
<li>smoking: Smoking status — e.g., “never smoked”, “still smoking”.</li>
<li>dmdx: Diabetes diagnosis — “yes” or “no”.</li>
<li>height: Height in meters (numeric).</li>
<li>weight: Weight in kilograms (numeric).</li>
<li>waist: Waist circumference in centimeters (numeric).</li>
<li>hip: Hip circumference in centimeters (numeric).</li>
<li>msbpr: Measured systolic blood pressure (numeric).</li>
<li>mdbpr: Measured diastolic blood pressure (numeric).</li>
<li>hba1c: Hemoglobin A1c (%) (numeric).</li>
<li>fbs: Fasting blood sugar in mmol/L — this is the outcome variable.</li>
<li>mogtt1h: Blood glucose level at 1 hour during OGTT (Oral Glucose Tolerance Test) (mmol/L).</li>
<li>mogtt2h: Blood glucose level at 2 hours during OGTT (mmol/L).</li>
<li>totchol: Total cholesterol (mmol/L).</li>
<li>ftrigliz: Fasting triglycerides (mmol/L).</li>
<li>hdl: High-density lipoprotein cholesterol (mmol/L).</li>
<li>ldl: Low-density lipoprotein cholesterol (mmol/L).</li>
<li>gender: Gender — “male” or “female”.</li>
<li>crural: Locality — “rural” or possibly “urban”.</li>
</ul>
</section>
<section id="load-the-dataset" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Load the dataset</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>data<span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"datamssm_a.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 4340 Columns: 21
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (6): codesub, hpt, smoking, dmdx, gender, crural
dbl (15): age, height, weight, waist, hip, msbpr, mdbpr, hba1c, fbs, mogtt1h...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 4,340
Columns: 21
$ codesub  &lt;chr&gt; "R-S615112", "MAA615089", "M-M616372", "MFM615361", "R-A61578…
$ age      &lt;dbl&gt; 70, 20, 29, 25, 37, 43, 26, 28, 48, 20, 56, 55, 26, 39, 18, 2…
$ hpt      &lt;chr&gt; "yes", "no", "no", "no", "no", "no", "no", "no", "no", "no", …
$ smoking  &lt;chr&gt; "never smoked", "still smoking", "never smoked", "still smoki…
$ dmdx     &lt;chr&gt; "no", "no", "no", "no", "no", "no", "no", "no", "no", "no", "…
$ height   &lt;dbl&gt; 1.54, 1.74, 1.54, 1.60, 1.44, 1.46, 1.47, 1.61, 1.68, 1.55, 1…
$ weight   &lt;dbl&gt; 40.0, 54.6, 37.0, 48.4, 44.5, 45.5, 48.0, 40.0, 48.4, 41.0, 5…
$ waist    &lt;dbl&gt; 76.0, 83.0, 83.0, 83.5, 85.0, 90.0, 91.0, 80.0, 82.0, 79.0, 9…
$ hip      &lt;dbl&gt; 61, 62, 63, 64, 64, 64, 64, 64, 65, 66, 67, 67, 67, 67, 67, 6…
$ msbpr    &lt;dbl&gt; 135.0, 105.0, 91.0, 117.0, 102.0, 124.0, 120.0, 85.0, 112.0, …
$ mdbpr    &lt;dbl&gt; 80.0, 58.0, 60.0, 68.5, 78.0, 65.5, 77.0, 60.0, 74.0, 52.0, 1…
$ hba1c    &lt;dbl&gt; 5.2, 5.3, 4.8, 4.8, 5.1, 5.1, 4.8, 4.9, 5.6, 4.2, 5.1, 5.3, 4…
$ fbs      &lt;dbl&gt; 3.99, 4.26, 4.94, 4.60, 4.60, 4.42, 3.82, 4.40, 4.80, 3.68, 6…
$ mogtt1h  &lt;dbl&gt; 7.06, 8.63, 6.26, 4.31, 9.49, 6.29, NA, 6.43, 9.23, 6.70, 8.7…
$ mogtt2h  &lt;dbl&gt; 3.22, 6.49, 5.15, 3.85, 7.71, 5.65, 5.88, 4.89, 4.29, 2.59, 7…
$ totchol  &lt;dbl&gt; 5.43, 5.13, 5.55, 4.01, 5.21, 6.19, 4.33, 5.84, 6.14, 6.02, 6…
$ ftrigliz &lt;dbl&gt; 1.06, 1.17, 0.72, 1.12, 0.78, 1.11, 0.73, 0.79, 1.63, 0.81, 1…
$ hdl      &lt;dbl&gt; 1.65, 1.59, 2.24, 1.21, 1.43, 2.18, 0.98, 1.81, 1.63, 1.47, 1…
$ ldl      &lt;dbl&gt; 2.69, 2.79, 2.55, 1.83, 2.40, 2.93, 1.82, 3.43, 3.71, 2.77, 3…
$ gender   &lt;chr&gt; "female", "male", "female", "male", "female", "female", "fema…
$ crural   &lt;chr&gt; "rural", "rural", "rural", "rural", "rural", "rural", "rural"…</code></pre>
</div>
</div>
</section>
<section id="data-wrangling" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Data wrangling</h1>
<p>Change character variable to factor</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>data<span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> <span class="fu">mutate_if</span>(is.character, <span class="sc">~</span><span class="fu">as_factor</span>(.))</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 4,340
Columns: 21
$ codesub  &lt;fct&gt; R-S615112, MAA615089, M-M616372, MFM615361, R-A615780, SAS615…
$ age      &lt;dbl&gt; 70, 20, 29, 25, 37, 43, 26, 28, 48, 20, 56, 55, 26, 39, 18, 2…
$ hpt      &lt;fct&gt; yes, no, no, no, no, no, no, no, no, no, yes, no, no, no, no,…
$ smoking  &lt;fct&gt; never smoked, still smoking, never smoked, still smoking, nev…
$ dmdx     &lt;fct&gt; no, no, no, no, no, no, no, no, no, no, no, no, no, no, no, n…
$ height   &lt;dbl&gt; 1.54, 1.74, 1.54, 1.60, 1.44, 1.46, 1.47, 1.61, 1.68, 1.55, 1…
$ weight   &lt;dbl&gt; 40.0, 54.6, 37.0, 48.4, 44.5, 45.5, 48.0, 40.0, 48.4, 41.0, 5…
$ waist    &lt;dbl&gt; 76.0, 83.0, 83.0, 83.5, 85.0, 90.0, 91.0, 80.0, 82.0, 79.0, 9…
$ hip      &lt;dbl&gt; 61, 62, 63, 64, 64, 64, 64, 64, 65, 66, 67, 67, 67, 67, 67, 6…
$ msbpr    &lt;dbl&gt; 135.0, 105.0, 91.0, 117.0, 102.0, 124.0, 120.0, 85.0, 112.0, …
$ mdbpr    &lt;dbl&gt; 80.0, 58.0, 60.0, 68.5, 78.0, 65.5, 77.0, 60.0, 74.0, 52.0, 1…
$ hba1c    &lt;dbl&gt; 5.2, 5.3, 4.8, 4.8, 5.1, 5.1, 4.8, 4.9, 5.6, 4.2, 5.1, 5.3, 4…
$ fbs      &lt;dbl&gt; 3.99, 4.26, 4.94, 4.60, 4.60, 4.42, 3.82, 4.40, 4.80, 3.68, 6…
$ mogtt1h  &lt;dbl&gt; 7.06, 8.63, 6.26, 4.31, 9.49, 6.29, NA, 6.43, 9.23, 6.70, 8.7…
$ mogtt2h  &lt;dbl&gt; 3.22, 6.49, 5.15, 3.85, 7.71, 5.65, 5.88, 4.89, 4.29, 2.59, 7…
$ totchol  &lt;dbl&gt; 5.43, 5.13, 5.55, 4.01, 5.21, 6.19, 4.33, 5.84, 6.14, 6.02, 6…
$ ftrigliz &lt;dbl&gt; 1.06, 1.17, 0.72, 1.12, 0.78, 1.11, 0.73, 0.79, 1.63, 0.81, 1…
$ hdl      &lt;dbl&gt; 1.65, 1.59, 2.24, 1.21, 1.43, 2.18, 0.98, 1.81, 1.63, 1.47, 1…
$ ldl      &lt;dbl&gt; 2.69, 2.79, 2.55, 1.83, 2.40, 2.93, 1.82, 3.43, 3.71, 2.77, 3…
$ gender   &lt;fct&gt; female, male, female, male, female, female, female, female, m…
$ crural   &lt;fct&gt; rural, rural, rural, rural, rural, rural, rural, rural, rural…</code></pre>
</div>
</div>
</section>
<section id="exploratory-data-analysis" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Exploratory Data Analysis</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      codesub          age         hpt                  smoking      dmdx     
 R-S615112:   1   Min.   :18.00   yes: 504   never smoked   :3307   no :3870  
 MAA615089:   1   1st Qu.:38.00   no :3836   still smoking  : 698   yes: 470  
 M-M616372:   1   Median :48.00              quitted smoking: 335             
 MFM615361:   1   Mean   :47.84                                               
 R-A615780:   1   3rd Qu.:58.00                                               
 SAS615496:   1   Max.   :89.00                                               
 (Other)  :4334                                                               
     height          weight           waist             hip        
 Min.   :1.270   Min.   : 30.00   Min.   : 50.80   Min.   : 61.00  
 1st Qu.:1.510   1st Qu.: 53.80   1st Qu.: 77.00   1st Qu.: 91.00  
 Median :1.560   Median : 62.00   Median : 86.00   Median : 97.00  
 Mean   :1.568   Mean   : 63.75   Mean   : 86.32   Mean   : 97.88  
 3rd Qu.:1.630   3rd Qu.: 71.97   3rd Qu.: 95.00   3rd Qu.:104.00  
 Max.   :1.960   Max.   :187.80   Max.   :154.50   Max.   :160.00  
 NA's   :1       NA's   :2        NA's   :2        NA's   :2       
     msbpr           mdbpr            hba1c             fbs        
 Min.   : 68.5   Min.   : 41.50   Min.   : 0.200   Min.   : 2.500  
 1st Qu.:117.0   1st Qu.: 70.00   1st Qu.: 5.100   1st Qu.: 4.480  
 Median :130.0   Median : 77.50   Median : 5.400   Median : 5.180  
 Mean   :133.5   Mean   : 78.47   Mean   : 5.805   Mean   : 5.734  
 3rd Qu.:146.5   3rd Qu.: 86.00   3rd Qu.: 5.800   3rd Qu.: 6.020  
 Max.   :237.0   Max.   :128.50   Max.   :15.000   Max.   :28.010  
                                  NA's   :70       NA's   :248     
    mogtt1h          mogtt2h          totchol          ftrigliz     
 Min.   : 0.160   Min.   : 0.160   Min.   : 0.180   Min.   : 0.110  
 1st Qu.: 6.540   1st Qu.: 5.150   1st Qu.: 4.970   1st Qu.: 0.930  
 Median : 8.590   Median : 6.600   Median : 5.700   Median : 1.260  
 Mean   : 9.106   Mean   : 7.343   Mean   : 5.792   Mean   : 1.534  
 3rd Qu.:10.840   3rd Qu.: 8.410   3rd Qu.: 6.530   3rd Qu.: 1.770  
 Max.   :41.500   Max.   :37.370   Max.   :23.140   Max.   :12.660  
 NA's   :604      NA's   :608      NA's   :54       NA's   :53      
      hdl             ldl            gender       crural    
 Min.   :0.080   Min.   : 0.140   female:2817   rural:2122  
 1st Qu.:1.110   1st Qu.: 2.790   male  :1523   urban:2218  
 Median :1.320   Median : 3.460                             
 Mean   :1.345   Mean   : 3.549                             
 3rd Qu.:1.540   3rd Qu.: 4.245                             
 Max.   :4.430   Max.   :10.560                             
 NA's   :52      NA's   :53                                 </code></pre>
</div>
</div>
<p>There are several data missing in the variable. Hence, we need to handle these missing data prior to continuing with analysis.</p>
<section id="handling-missing-data" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="handling-missing-data"><span class="header-section-number">6.1</span> Handling missing data</h2>
<p>In this practice, we remove any row with missing data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>clean_data <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(data)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(clean_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      codesub          age         hpt                  smoking      dmdx     
 R-S615112:   1   Min.   :18.00   yes: 316   never smoked   :2718   no :3509  
 MAA615089:   1   1st Qu.:37.00   no :3230   still smoking  : 569   yes:  37  
 M-M616372:   1   Median :47.00              quitted smoking: 259             
 MFM615361:   1   Mean   :46.91                                               
 R-A615780:   1   3rd Qu.:57.00                                               
 SAS615496:   1   Max.   :89.00                                               
 (Other)  :3540                                                               
     height          weight          waist            hip        
 Min.   :1.270   Min.   : 30.0   Min.   : 50.8   Min.   : 61.00  
 1st Qu.:1.510   1st Qu.: 53.4   1st Qu.: 76.0   1st Qu.: 91.00  
 Median :1.560   Median : 62.0   Median : 85.0   Median : 97.00  
 Mean   :1.569   Mean   : 63.5   Mean   : 85.7   Mean   : 97.68  
 3rd Qu.:1.630   3rd Qu.: 71.7   3rd Qu.: 94.0   3rd Qu.:104.00  
 Max.   :1.960   Max.   :187.8   Max.   :154.5   Max.   :160.00  
                                                                 
     msbpr           mdbpr            hba1c            fbs        
 Min.   : 68.5   Min.   : 41.50   Min.   : 3.80   Min.   : 2.500  
 1st Qu.:116.1   1st Qu.: 70.00   1st Qu.: 5.10   1st Qu.: 4.400  
 Median :129.0   Median : 77.50   Median : 5.40   Median : 5.060  
 Mean   :132.8   Mean   : 78.13   Mean   : 5.53   Mean   : 5.298  
 3rd Qu.:145.5   3rd Qu.: 85.50   3rd Qu.: 5.70   3rd Qu.: 5.750  
 Max.   :237.0   Max.   :128.50   Max.   :15.00   Max.   :23.090  
                                                                  
    mogtt1h          mogtt2h          totchol          ftrigliz     
 Min.   : 0.160   Min.   : 0.160   Min.   : 1.170   Min.   : 0.180  
 1st Qu.: 6.660   1st Qu.: 5.240   1st Qu.: 4.950   1st Qu.: 0.900  
 Median : 8.650   Median : 6.685   Median : 5.700   Median : 1.220  
 Mean   : 9.208   Mean   : 7.436   Mean   : 5.770   Mean   : 1.484  
 3rd Qu.:10.910   3rd Qu.: 8.480   3rd Qu.: 6.497   3rd Qu.: 1.710  
 Max.   :41.500   Max.   :37.370   Max.   :23.140   Max.   :12.660  
                                                                    
      hdl             ldl            gender       crural    
 Min.   :0.080   Min.   : 0.150   female:2334   rural:1694  
 1st Qu.:1.110   1st Qu.: 2.780   male  :1212   urban:1852  
 Median :1.330   Median : 3.440                             
 Mean   :1.356   Mean   : 3.523                             
 3rd Qu.:1.560   3rd Qu.: 4.200                             
 Max.   :4.430   Max.   :10.560                             
                                                            </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(clean_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 3,546
Columns: 21
$ codesub  &lt;fct&gt; R-S615112, MAA615089, M-M616372, MFM615361, R-A615780, SAS615…
$ age      &lt;dbl&gt; 70, 20, 29, 25, 37, 43, 28, 48, 20, 56, 55, 26, 39, 18, 21, 2…
$ hpt      &lt;fct&gt; yes, no, no, no, no, no, no, no, no, yes, no, no, no, no, no,…
$ smoking  &lt;fct&gt; never smoked, still smoking, never smoked, still smoking, nev…
$ dmdx     &lt;fct&gt; no, no, no, no, no, no, no, no, no, no, no, no, no, no, no, n…
$ height   &lt;dbl&gt; 1.54, 1.74, 1.54, 1.60, 1.44, 1.46, 1.61, 1.68, 1.55, 1.59, 1…
$ weight   &lt;dbl&gt; 40.0, 54.6, 37.0, 48.4, 44.5, 45.5, 40.0, 48.4, 41.0, 52.6, 4…
$ waist    &lt;dbl&gt; 76.0, 83.0, 83.0, 83.5, 85.0, 90.0, 80.0, 82.0, 79.0, 93.4, 8…
$ hip      &lt;dbl&gt; 61, 62, 63, 64, 64, 64, 64, 65, 66, 67, 67, 67, 67, 67, 68, 6…
$ msbpr    &lt;dbl&gt; 135.0, 105.0, 91.0, 117.0, 102.0, 124.0, 85.0, 112.0, 108.0, …
$ mdbpr    &lt;dbl&gt; 80.0, 58.0, 60.0, 68.5, 78.0, 65.5, 60.0, 74.0, 52.0, 109.0, …
$ hba1c    &lt;dbl&gt; 5.2, 5.3, 4.8, 4.8, 5.1, 5.1, 4.9, 5.6, 4.2, 5.1, 5.3, 4.8, 5…
$ fbs      &lt;dbl&gt; 3.99, 4.26, 4.94, 4.60, 4.60, 4.42, 4.40, 4.80, 3.68, 6.28, 6…
$ mogtt1h  &lt;dbl&gt; 7.06, 8.63, 6.26, 4.31, 9.49, 6.29, 6.43, 9.23, 6.70, 8.77, 4…
$ mogtt2h  &lt;dbl&gt; 3.22, 6.49, 5.15, 3.85, 7.71, 5.65, 4.89, 4.29, 2.59, 7.94, 5…
$ totchol  &lt;dbl&gt; 5.43, 5.13, 5.55, 4.01, 5.21, 6.19, 5.84, 6.14, 6.02, 6.13, 8…
$ ftrigliz &lt;dbl&gt; 1.06, 1.17, 0.72, 1.12, 0.78, 1.11, 0.79, 1.63, 0.81, 1.37, 0…
$ hdl      &lt;dbl&gt; 1.65, 1.59, 2.24, 1.21, 1.43, 2.18, 1.81, 1.63, 1.47, 1.57, 1…
$ ldl      &lt;dbl&gt; 2.69, 2.79, 2.55, 1.83, 2.40, 2.93, 3.43, 3.71, 2.77, 3.98, 5…
$ gender   &lt;fct&gt; female, male, female, male, female, female, female, male, fem…
$ crural   &lt;fct&gt; rural, rural, rural, rural, rural, rural, rural, rural, rural…</code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>clean_data <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="sc">-</span>codesub) <span class="sc">%&gt;%</span> </span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tbl_summary</span>(<span class="at">statistic =</span> <span class="fu">list</span>(<span class="fu">all_continuous</span>()<span class="sc">~</span> <span class="st">"{mean} ({sd})"</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">modify_caption</span>(<span class="st">"**Table 1:Characteristic of Participant**"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="diuzwcdjkx" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#diuzwcdjkx table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#diuzwcdjkx thead, #diuzwcdjkx tbody, #diuzwcdjkx tfoot, #diuzwcdjkx tr, #diuzwcdjkx td, #diuzwcdjkx th {
  border-style: none;
}

#diuzwcdjkx p {
  margin: 0;
  padding: 0;
}

#diuzwcdjkx .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#diuzwcdjkx .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#diuzwcdjkx .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#diuzwcdjkx .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#diuzwcdjkx .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#diuzwcdjkx .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#diuzwcdjkx .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#diuzwcdjkx .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#diuzwcdjkx .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#diuzwcdjkx .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#diuzwcdjkx .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#diuzwcdjkx .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#diuzwcdjkx .gt_spanner_row {
  border-bottom-style: hidden;
}

#diuzwcdjkx .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#diuzwcdjkx .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#diuzwcdjkx .gt_from_md > :first-child {
  margin-top: 0;
}

#diuzwcdjkx .gt_from_md > :last-child {
  margin-bottom: 0;
}

#diuzwcdjkx .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#diuzwcdjkx .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#diuzwcdjkx .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#diuzwcdjkx .gt_row_group_first td {
  border-top-width: 2px;
}

#diuzwcdjkx .gt_row_group_first th {
  border-top-width: 2px;
}

#diuzwcdjkx .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#diuzwcdjkx .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#diuzwcdjkx .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#diuzwcdjkx .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#diuzwcdjkx .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#diuzwcdjkx .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#diuzwcdjkx .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#diuzwcdjkx .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#diuzwcdjkx .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#diuzwcdjkx .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#diuzwcdjkx .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#diuzwcdjkx .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#diuzwcdjkx .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#diuzwcdjkx .gt_left {
  text-align: left;
}

#diuzwcdjkx .gt_center {
  text-align: center;
}

#diuzwcdjkx .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#diuzwcdjkx .gt_font_normal {
  font-weight: normal;
}

#diuzwcdjkx .gt_font_bold {
  font-weight: bold;
}

#diuzwcdjkx .gt_font_italic {
  font-style: italic;
}

#diuzwcdjkx .gt_super {
  font-size: 65%;
}

#diuzwcdjkx .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#diuzwcdjkx .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#diuzwcdjkx .gt_indent_1 {
  text-indent: 5px;
}

#diuzwcdjkx .gt_indent_2 {
  text-indent: 10px;
}

#diuzwcdjkx .gt_indent_3 {
  text-indent: 15px;
}

#diuzwcdjkx .gt_indent_4 {
  text-indent: 20px;
}

#diuzwcdjkx .gt_indent_5 {
  text-indent: 25px;
}

#diuzwcdjkx .katex-display {
  display: inline-flex !important;
  margin-bottom: 0.75em !important;
}

#diuzwcdjkx div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {
  height: 0px !important;
}
</style>

<table class="gt_table caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
<caption><strong>Table 1:Characteristic of Participant</strong></caption>
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="gt_col_headings header">
<th id="label" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" scope="col"><strong>Characteristic</strong></th>
<th id="stat_0" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col"><strong>N = 3,546</strong><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;"><sup>1</sup></span></th>
</tr>
</thead>
<tbody class="gt_table_body">
<tr class="odd">
<td class="gt_row gt_left" headers="label">age</td>
<td class="gt_row gt_center" headers="stat_0">47 (14)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">hpt</td>
<td class="gt_row gt_center" headers="stat_0">316 (8.9%)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">smoking</td>
<td class="gt_row gt_center" headers="stat_0"><br>
</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;never smoked</td>
<td class="gt_row gt_center" headers="stat_0">2,718 (77%)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;still smoking</td>
<td class="gt_row gt_center" headers="stat_0">569 (16%)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;quitted smoking</td>
<td class="gt_row gt_center" headers="stat_0">259 (7.3%)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">dmdx</td>
<td class="gt_row gt_center" headers="stat_0">37 (1.0%)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">height</td>
<td class="gt_row gt_center" headers="stat_0">1.57 (0.09)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">weight</td>
<td class="gt_row gt_center" headers="stat_0">64 (14)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">waist</td>
<td class="gt_row gt_center" headers="stat_0">86 (13)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">hip</td>
<td class="gt_row gt_center" headers="stat_0">98 (11)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">msbpr</td>
<td class="gt_row gt_center" headers="stat_0">133 (23)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">mdbpr</td>
<td class="gt_row gt_center" headers="stat_0">78 (12)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">hba1c</td>
<td class="gt_row gt_center" headers="stat_0">5.53 (0.97)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">fbs</td>
<td class="gt_row gt_center" headers="stat_0">5.30 (1.85)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">mogtt1h</td>
<td class="gt_row gt_center" headers="stat_0">9.2 (3.8)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">mogtt2h</td>
<td class="gt_row gt_center" headers="stat_0">7.4 (3.7)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">totchol</td>
<td class="gt_row gt_center" headers="stat_0">5.77 (1.27)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">ftrigliz</td>
<td class="gt_row gt_center" headers="stat_0">1.48 (1.02)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">hdl</td>
<td class="gt_row gt_center" headers="stat_0">1.36 (0.37)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">ldl</td>
<td class="gt_row gt_center" headers="stat_0">3.52 (1.10)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">gender</td>
<td class="gt_row gt_center" headers="stat_0"><br>
</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;female</td>
<td class="gt_row gt_center" headers="stat_0">2,334 (66%)</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;male</td>
<td class="gt_row gt_center" headers="stat_0">1,212 (34%)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">crural</td>
<td class="gt_row gt_center" headers="stat_0"><br>
</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;rural</td>
<td class="gt_row gt_center" headers="stat_0">1,694 (48%)</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;urban</td>
<td class="gt_row gt_center" headers="stat_0">1,852 (52%)</td>
</tr>
</tbody><tfoot class="gt_footnotes">
<tr class="odd">
<td colspan="2" class="gt_footnote"><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;"><sup>1</sup></span> Mean (SD); n (%)</td>
</tr>
</tfoot>

</table>

</div>
</div>
</div>
</section>
<section id="categorize-fbs-into-3-levels" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="categorize-fbs-into-3-levels"><span class="header-section-number">6.2</span> Categorize fbs into 3 levels</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Categorize FBS based on Malaysian clinical cut-offs</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>clean_data <span class="ot">&lt;-</span> clean_data <span class="sc">%&gt;%</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">cat_fbs =</span> <span class="fu">case_when</span>(</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>    fbs <span class="sc">&lt;</span> <span class="fl">5.6</span> <span class="sc">~</span> <span class="st">"Normal"</span>,</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>    fbs <span class="sc">&gt;=</span> <span class="fl">5.6</span> <span class="sc">&amp;</span> fbs <span class="sc">&lt;=</span> <span class="fl">6.9</span> <span class="sc">~</span> <span class="st">"Prediabetes"</span>,</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>    <span class="cn">TRUE</span> <span class="sc">~</span> <span class="st">"Diabetes"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">cat_fbs =</span> <span class="fu">factor</span>(cat_fbs, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Normal"</span>, <span class="st">"Prediabetes"</span>, <span class="st">"Diabetes"</span>)))</span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Check result</span></span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(clean_data<span class="sc">$</span>cat_fbs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
     Normal Prediabetes    Diabetes 
       2497         746         303 </code></pre>
</div>
</div>
</section>
<section id="checking-level-of-cat_fbs" class="level2" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="checking-level-of-cat_fbs"><span class="header-section-number">6.3</span> Checking level of cat_fbs</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">levels</span>(clean_data<span class="sc">$</span>cat_fbs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Normal"      "Prediabetes" "Diabetes"   </code></pre>
</div>
</div>
</section>
<section id="re-level-for-cat_fbs" class="level2" data-number="6.4">
<h2 data-number="6.4" class="anchored" data-anchor-id="re-level-for-cat_fbs"><span class="header-section-number">6.4</span> Re-level for cat_fbs</h2>
<p>We will use VGAM package for further multinomial analysis. As the packages compare biggest value to the lowest, we need to rearrage the level of cat_fbs. We will make “Normal” as the reference category.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>clean_data<span class="ot">&lt;-</span> clean_data <span class="sc">%&gt;%</span> </span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">cat_fbs2 =</span> <span class="fu">fct_relevel</span>(cat_fbs,</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>                                <span class="fu">c</span>(<span class="st">"Diabetes"</span>, <span class="st">"Prediabetes"</span>, <span class="st">"Normal"</span>)))</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a><span class="co"># compare the data</span></span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(clean_data<span class="sc">$</span>cat_fbs); <span class="fu">summary</span>(clean_data<span class="sc">$</span>cat_fbs2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     Normal Prediabetes    Diabetes 
       2497         746         303 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>   Diabetes Prediabetes      Normal 
        303         746        2497 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># recheck releveling</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="fu">levels</span>(clean_data<span class="sc">$</span>cat_fbs2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Diabetes"    "Prediabetes" "Normal"     </code></pre>
</div>
</div>
</section>
</section>
<section id="multinomial-analysis-using-vgam-packages" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> Multinomial analysis using VGAM packages</h1>
<p>We will be using VGAM packages to run multinomial logistic regression. The model that we want to estimate for are: 1. group 1 vs group 3: Diabetes vs Normal 2. group 2 vs group 3: Prediabetes vs Normal</p>
<p>The reference group here, is Normal group.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(VGAM)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'VGAM' was built under R version 4.4.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: stats4</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: splines</code></pre>
</div>
</div>
<section id="model-with-univariable" class="level2" data-number="7.1">
<h2 data-number="7.1" class="anchored" data-anchor-id="model-with-univariable"><span class="header-section-number">7.1</span> Model with univariable</h2>
<section id="gender" class="level3" data-number="7.1.1">
<h3 data-number="7.1.1" class="anchored" data-anchor-id="gender"><span class="header-section-number">7.1.1</span> Gender</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>mod1<span class="ot">&lt;-</span> <span class="fu">vglm</span>(cat_fbs2<span class="sc">~</span> gender, multinomial, <span class="at">data =</span> clean_data)</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
vglm(formula = cat_fbs2 ~ gender, family = multinomial, data = clean_data)

Coefficients: 
              Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept):1 -2.13590    0.07515 -28.423  &lt; 2e-16 ***
(Intercept):2 -1.29294    0.05264 -24.564  &lt; 2e-16 ***
gendermale:1   0.07934    0.12802   0.620  0.53545    
gendermale:2   0.23841    0.08652   2.756  0.00586 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Names of linear predictors: log(mu[,1]/mu[,3]), log(mu[,2]/mu[,3])

Residual deviance: 5560.465 on 7088 degrees of freedom

Log-likelihood: -2780.233 on 7088 degrees of freedom

Number of Fisher scoring iterations: 5 

No Hauck-Donner effect found in any of the estimates


Reference group is level  3  of the response</code></pre>
</div>
</div>
<p>Intercept 1: for outcome cat_fbs2 = diabetes vs normal. (Intercept):1 = -2.13590. This value represents the log-odds of being in the Diabetes group rather than the Normal group for individuals in the reference category, which is female. The coefficient is statistically significant (p &lt; 0.001), indicating a meaningful difference. Since the log-odds value is negative, it suggests that females have a low likelihood of being diabetic compared to having normal fasting blood sugar levels.</p>
<p>Intercept 2: for outcome cat_fbs2 = prediabetes vs normal. (Intercept):2 = -1.29294. This coefficient represents the log-odds of being in the Prediabetes group rather than the Normal group for individuals in the reference category, which is female. It is statistically significant (p &lt; 0.001), indicating a strong association. The negative value suggests that females have lower odds of being prediabetic compared to having normal fasting blood sugar levels.</p>
<p>gendermale:1 for outcome cat_fbs 2 = diabetes vs normal. gendermale:1 = 0.07934 (p = 0.53545). This coefficient reflects the change in log-odds of being in the Diabetes group versus the Normal group for males compared to females. The result is not statistically significant (p &gt; 0.05), indicating that gender does not have a meaningful association with the likelihood of diabetes compared to normal fasting blood sugar levels in this model.</p>
<p>gendermale:2 for outcome cat_fbs2 = prediabetes vs normal. This coefficient represents the change in log-odds of being in the Prediabetes group compared to the Normal group for males relative to females. The association is statistically significant, indicating that males are significantly more likely to be prediabetic than females when compared to having normal fasting blood sugar levels.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fl">0.23841</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.269229</code></pre>
</div>
</div>
<p>So, males have 1.27 times the odds of being prediabetic vs normal compared to females.</p>
</section>
<section id="age" class="level3" data-number="7.1.2">
<h3 data-number="7.1.2" class="anchored" data-anchor-id="age"><span class="header-section-number">7.1.2</span> Age</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>mod2<span class="ot">&lt;-</span> <span class="fu">vglm</span>(cat_fbs2 <span class="sc">~</span> age, multinomial, <span class="at">data =</span> clean_data)</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
vglm(formula = cat_fbs2 ~ age, family = multinomial, data = clean_data)

Coefficients: 
               Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept):1 -3.556889   0.227492  -15.63  &lt; 2e-16 ***
(Intercept):2 -2.700052   0.156258  -17.28  &lt; 2e-16 ***
age:1          0.030088   0.004342    6.93 4.22e-12 ***
age:2          0.030949   0.003019   10.25  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Names of linear predictors: log(mu[,1]/mu[,3]), log(mu[,2]/mu[,3])

Residual deviance: 5429.641 on 7088 degrees of freedom

Log-likelihood: -2714.821 on 7088 degrees of freedom

Number of Fisher scoring iterations: 5 

Warning: Hauck-Donner effect detected in the following estimate(s):
'(Intercept):1'


Reference group is level  3  of the response</code></pre>
</div>
</div>
<p>age:1 for outcome cat_fbs 2 = diabetes vs normal. age:1 0.030088. Each 1-year increase in age is associated with a 3.1% increase in odds of being diabetic vs normal</p>
<p>age:2 for outcome cat_fbs2 = prediabetes vs normal. age:2 0.030949. Each 1-year increase in age is associated with a 3.2% increase in odds of being prediabetic vs normal</p>
<p>Age is significantly associated with both diabetes and prediabetes, compared to normal FBS. For each additional year of age:</p>
<p>The odds of having diabetes (vs normal FBS) increase by ~3.1%</p>
<p>The odds of having prediabetes (vs normal FBS) increase by ~3.2%</p>
<p>This indicates that older individuals are more likely to have impaired fasting blood sugar.</p>
</section>
</section>
<section id="multivariate-model-analysis" class="level2" data-number="7.2">
<h2 data-number="7.2" class="anchored" data-anchor-id="multivariate-model-analysis"><span class="header-section-number">7.2</span> Multivariate Model Analysis</h2>
<p>Adding more variable into the model. We will choose variables as follows: - age - gender - hpt</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>mod3 <span class="ot">&lt;-</span><span class="fu">vglm</span>(cat_fbs2<span class="sc">~</span>age<span class="sc">+</span>gender<span class="sc">+</span>hpt, multinomial, <span class="at">data=</span>clean_data)</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
vglm(formula = cat_fbs2 ~ age + gender + hpt, family = multinomial, 
    data = clean_data)

Coefficients: 
               Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept):1 -3.004827   0.317364  -9.468  &lt; 2e-16 ***
(Intercept):2 -2.044292   0.220406  -9.275  &lt; 2e-16 ***
age:1          0.027673   0.004467   6.195 5.82e-10 ***
age:2          0.027503   0.003102   8.865  &lt; 2e-16 ***
gendermale:1   0.063200   0.129306   0.489  0.62501    
gendermale:2   0.224657   0.088405   2.541  0.01105 *  
hptno:1       -0.505750   0.192373  -2.629  0.00856 ** 
hptno:2       -0.633716   0.135581  -4.674 2.95e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Names of linear predictors: log(mu[,1]/mu[,3]), log(mu[,2]/mu[,3])

Residual deviance: 5400.516 on 7084 degrees of freedom

Log-likelihood: -2700.258 on 7084 degrees of freedom

Number of Fisher scoring iterations: 5 

Warning: Hauck-Donner effect detected in the following estimate(s):
'(Intercept):1'


Reference group is level  3  of the response</code></pre>
</div>
</div>
</section>
</section>
<section id="multinomial-analysis-using-nnet-package" class="level1" data-number="8">
<h1 data-number="8"><span class="header-section-number">8</span> Multinomial analysis using NNET package</h1>
<p>Unlike VGAM::vglm function where the reference or the base outcome in the largest group (level), the nnet::multinom usess the smallest group (level) as the references or base outcome.</p>
<section id="load-the-packages" class="level2" data-number="8.1">
<h2 data-number="8.1" class="anchored" data-anchor-id="load-the-packages"><span class="header-section-number">8.1</span> Load the packages</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(nnet)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'nnet' was built under R version 4.4.3</code></pre>
</div>
</div>
</section>
<section id="univariate-model" class="level2" data-number="8.2">
<h2 data-number="8.2" class="anchored" data-anchor-id="univariate-model"><span class="header-section-number">8.2</span> Univariate model</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>mlog_nnet<span class="ot">&lt;-</span> <span class="fu">multinom</span>(cat_fbs <span class="sc">~</span> age, <span class="at">data=</span> clean_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># weights:  9 (4 variable)
initial  value 3895.679176 
iter  10 value 2722.946624
final  value 2714.820772 
converged</code></pre>
</div>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mlog_nnet)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
multinom(formula = cat_fbs ~ age, data = clean_data)

Coefficients:
            (Intercept)        age
Prediabetes   -2.700050 0.03094930
Diabetes      -3.556868 0.03008734

Std. Errors:
            (Intercept)         age
Prediabetes   0.1562583 0.003018554
Diabetes      0.2274918 0.004341841

Residual Deviance: 5429.642 
AIC: 5437.642 </code></pre>
</div>
</div>
</section>
<section id="comparing-vgamvglm-and-nnetmultinom" class="level2" data-number="8.3">
<h2 data-number="8.3" class="anchored" data-anchor-id="comparing-vgamvglm-and-nnetmultinom"><span class="header-section-number">8.3</span> Comparing VGAM::vglm and nnet::multinom</h2>
<p>Changing the reference category</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>clean_data <span class="ot">&lt;-</span> clean_data <span class="sc">%&gt;%</span> </span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">cat_fbs_relev=</span> <span class="fu">relevel</span>(cat_fbs, <span class="at">ref =</span> <span class="st">"Normal"</span>))</span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a><span class="fu">levels</span>(clean_data<span class="sc">$</span>cat_fbs_relev)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Normal"      "Prediabetes" "Diabetes"   </code></pre>
</div>
</div>
<p>So, running multinom will give the following:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>mlog_nnet_relev <span class="ot">&lt;-</span> <span class="fu">multinom</span>(cat_fbs_relev<span class="sc">~</span> age, <span class="at">data =</span> clean_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># weights:  9 (4 variable)
initial  value 3895.679176 
iter  10 value 2722.946624
final  value 2714.820772 
converged</code></pre>
</div>
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mlog_nnet_relev)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
multinom(formula = cat_fbs_relev ~ age, data = clean_data)

Coefficients:
            (Intercept)        age
Prediabetes   -2.700050 0.03094930
Diabetes      -3.556868 0.03008734

Std. Errors:
            (Intercept)         age
Prediabetes   0.1562583 0.003018554
Diabetes      0.2274918 0.004341841

Residual Deviance: 5429.642 
AIC: 5437.642 </code></pre>
</div>
</div>
<p>And running vglm, we will get this:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
vglm(formula = cat_fbs2 ~ age, family = multinomial, data = clean_data)

Coefficients: 
               Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept):1 -3.556889   0.227492  -15.63  &lt; 2e-16 ***
(Intercept):2 -2.700052   0.156258  -17.28  &lt; 2e-16 ***
age:1          0.030088   0.004342    6.93 4.22e-12 ***
age:2          0.030949   0.003019   10.25  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Names of linear predictors: log(mu[,1]/mu[,3]), log(mu[,2]/mu[,3])

Residual deviance: 5429.641 on 7088 degrees of freedom

Log-likelihood: -2714.821 on 7088 degrees of freedom

Number of Fisher scoring iterations: 5 

Warning: Hauck-Donner effect detected in the following estimate(s):
'(Intercept):1'


Reference group is level  3  of the response</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(mod2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                    2.5 %      97.5 %
(Intercept):1 -4.00276650 -3.11101242
(Intercept):2 -3.00631271 -2.39379144
age:1          0.02157782  0.03859756
age:2          0.02503309  0.03686560</code></pre>
</div>
</div>
</section>
</section>
<section id="inferences" class="level1" data-number="9">
<h1 data-number="9"><span class="header-section-number">9</span> Inferences</h1>
<section id="using-vgam" class="level2" data-number="9.1">
<h2 data-number="9.1" class="anchored" data-anchor-id="using-vgam"><span class="header-section-number">9.1</span> Using VGAM</h2>
<p>Getting the beta coefficient and confidence interval for each covariate in multivariate model (mod3)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a>b_mod3 <span class="ot">&lt;-</span> <span class="fu">coef</span>(mod3)</span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a>ci_mod3 <span class="ot">&lt;-</span> <span class="fu">confint</span>(mod3)</span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a><span class="fu">cbind</span>(b_mod3, ci_mod3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                   b_mod3       2.5 %      97.5 %
(Intercept):1 -3.00482660 -3.62684834 -2.38280486
(Intercept):2 -2.04429153 -2.47627871 -1.61230436
age:1          0.02767322  0.01891851  0.03642794
age:2          0.02750283  0.02142222  0.03358344
gendermale:1   0.06320003 -0.19023495  0.31663501
gendermale:2   0.22465701  0.05138548  0.39792854
hptno:1       -0.50575028 -0.88279469 -0.12870587
hptno:2       -0.63371553 -0.89944971 -0.36798135</code></pre>
</div>
</div>
<p>The following sequences will; 1. return the log odds and the RRR 2. return the 95%CI for log odds and the CI for RRR 3. combine the objects into table 3. renaming the column</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a>b_rrr_mod3 <span class="ot">&lt;-</span> <span class="fu">cbind</span>(<span class="fu">coef</span>(mod3), <span class="fu">exp</span>(<span class="fu">coef</span>(mod3)))</span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a>ci_b_rrr.mod3 <span class="ot">&lt;-</span><span class="fu">cbind</span>(<span class="fu">confint</span>(mod3), <span class="fu">exp</span>(<span class="fu">confint</span>(mod3)))</span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a>res_mod3<span class="ot">&lt;-</span> <span class="fu">cbind</span>(b_rrr_mod3, ci_b_rrr.mod3)</span>
<span id="cb64-4"><a href="#cb64-4" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(res_mod3)<span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">'b'</span>,<span class="st">'rrr'</span>,</span>
<span id="cb64-5"><a href="#cb64-5" aria-hidden="true" tabindex="-1"></a>                       <span class="st">'lower 95% b'</span>, <span class="st">'upper 95% b'</span>,</span>
<span id="cb64-6"><a href="#cb64-6" aria-hidden="true" tabindex="-1"></a>                       <span class="st">'lower 95% rrr'</span>, <span class="st">'upper 95% rrr'</span>)</span>
<span id="cb64-7"><a href="#cb64-7" aria-hidden="true" tabindex="-1"></a>res_mod3</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                        b        rrr lower 95% b upper 95% b lower 95% rrr
(Intercept):1 -3.00482660 0.04954735 -3.62684834 -2.38280486    0.02659989
(Intercept):2 -2.04429153 0.12947188 -2.47627871 -1.61230436    0.08405544
age:1          0.02767322 1.02805968  0.01891851  0.03642794    1.01909860
age:2          0.02750283 1.02788453  0.02142222  0.03358344    1.02165333
gendermale:1   0.06320003 1.06523990 -0.19023495  0.31663501    0.82676486
gendermale:2   0.22465701 1.25189325  0.05138548  0.39792854    1.05272862
hptno:1       -0.50575028 0.60305295 -0.88279469 -0.12870587    0.41362534
hptno:2       -0.63371553 0.53061661 -0.89944971 -0.36798135    0.40679345
              upper 95% rrr
(Intercept):1    0.09229135
(Intercept):2    0.19942753
age:1            1.03709956
age:2            1.03415373
gendermale:1     1.37250154
gendermale:2     1.48873764
hptno:1          0.87923254
hptno:2          0.69213009</code></pre>
</div>
</div>
<p>A better table using knitr and kableExtra packages</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'knitr' was built under R version 4.4.3</code></pre>
</div>
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(kableExtra)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(res_mod3, <span class="at">digits =</span> <span class="dv">3</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">bootstrap_options =</span> </span>
<span id="cb69-3"><a href="#cb69-3" aria-hidden="true" tabindex="-1"></a>                  <span class="fu">c</span>(<span class="st">"striped"</span>, <span class="st">"hover"</span>, <span class="st">"condensed"</span>, <span class="st">"responsive"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="table-responsive">
<table class="table table-striped table-hover table-condensed caption-top table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th">b</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">rrr</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">lower 95% b</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">upper 95% b</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">lower 95% rrr</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">upper 95% rrr</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept):1</td>
<td style="text-align: right;">-3.005</td>
<td style="text-align: right;">0.050</td>
<td style="text-align: right;">-3.627</td>
<td style="text-align: right;">-2.383</td>
<td style="text-align: right;">0.027</td>
<td style="text-align: right;">0.092</td>
</tr>
<tr class="even">
<td style="text-align: left;">(Intercept):2</td>
<td style="text-align: right;">-2.044</td>
<td style="text-align: right;">0.129</td>
<td style="text-align: right;">-2.476</td>
<td style="text-align: right;">-1.612</td>
<td style="text-align: right;">0.084</td>
<td style="text-align: right;">0.199</td>
</tr>
<tr class="odd">
<td style="text-align: left;">age:1</td>
<td style="text-align: right;">0.028</td>
<td style="text-align: right;">1.028</td>
<td style="text-align: right;">0.019</td>
<td style="text-align: right;">0.036</td>
<td style="text-align: right;">1.019</td>
<td style="text-align: right;">1.037</td>
</tr>
<tr class="even">
<td style="text-align: left;">age:2</td>
<td style="text-align: right;">0.028</td>
<td style="text-align: right;">1.028</td>
<td style="text-align: right;">0.021</td>
<td style="text-align: right;">0.034</td>
<td style="text-align: right;">1.022</td>
<td style="text-align: right;">1.034</td>
</tr>
<tr class="odd">
<td style="text-align: left;">gendermale:1</td>
<td style="text-align: right;">0.063</td>
<td style="text-align: right;">1.065</td>
<td style="text-align: right;">-0.190</td>
<td style="text-align: right;">0.317</td>
<td style="text-align: right;">0.827</td>
<td style="text-align: right;">1.373</td>
</tr>
<tr class="even">
<td style="text-align: left;">gendermale:2</td>
<td style="text-align: right;">0.225</td>
<td style="text-align: right;">1.252</td>
<td style="text-align: right;">0.051</td>
<td style="text-align: right;">0.398</td>
<td style="text-align: right;">1.053</td>
<td style="text-align: right;">1.489</td>
</tr>
<tr class="odd">
<td style="text-align: left;">hptno:1</td>
<td style="text-align: right;">-0.506</td>
<td style="text-align: right;">0.603</td>
<td style="text-align: right;">-0.883</td>
<td style="text-align: right;">-0.129</td>
<td style="text-align: right;">0.414</td>
<td style="text-align: right;">0.879</td>
</tr>
<tr class="even">
<td style="text-align: left;">hptno:2</td>
<td style="text-align: right;">-0.634</td>
<td style="text-align: right;">0.531</td>
<td style="text-align: right;">-0.899</td>
<td style="text-align: right;">-0.368</td>
<td style="text-align: right;">0.407</td>
<td style="text-align: right;">0.692</td>
</tr>
</tbody>
</table>
</div>


</div>
</div>
</section>
<section id="using-nnet-packages" class="level2" data-number="9.2">
<h2 data-number="9.2" class="anchored" data-anchor-id="using-nnet-packages"><span class="header-section-number">9.2</span> Using NNET packages</h2>
</section>
<section id="getting-p-value-and-ci-from-nnetmultinom" class="level2" data-number="9.3">
<h2 data-number="9.3" class="anchored" data-anchor-id="getting-p-value-and-ci-from-nnetmultinom"><span class="header-section-number">9.3</span> Getting p-value and CI from nnet::multinom</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a>z.test<span class="ot">&lt;-</span> <span class="fu">summary</span>(mlog_nnet_relev)<span class="sc">$</span>coefficients<span class="sc">/</span><span class="fu">summary</span>(mlog_nnet_relev)<span class="sc">$</span>standard.errors</span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a><span class="co"># 2-tailed</span></span>
<span id="cb70-3"><a href="#cb70-3" aria-hidden="true" tabindex="-1"></a>p.val <span class="ot">&lt;-</span> (<span class="dv">1</span><span class="sc">-</span><span class="fu">pnorm</span>(<span class="fu">abs</span>(z.test), <span class="dv">0</span>, <span class="dv">1</span>))<span class="sc">*</span><span class="dv">2</span></span>
<span id="cb70-4"><a href="#cb70-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'readxl' was built under R version 4.4.3</code></pre>
</div>
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(p.val)<span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"p-val intercept"</span>, <span class="st">"p-val age"</span>)</span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a>p.val</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            p-val intercept    p-val age
Prediabetes               0 0.000000e+00
Diabetes                  0 4.219514e-12</code></pre>
</div>
</div>
</section>
<section id="ci-for-nnetmultinom" class="level2" data-number="9.4">
<h2 data-number="9.4" class="anchored" data-anchor-id="ci-for-nnetmultinom"><span class="header-section-number">9.4</span> CI for nnet::multinom</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(mlog_nnet_relev, <span class="at">level =</span> <span class="fl">0.95</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>, , Prediabetes

                  2.5 %      97.5 %
(Intercept) -3.00631034 -2.39378914
age          0.02503305  0.03686556

, , Diabetes

                  2.5 %      97.5 %
(Intercept) -4.00274387 -3.11099226
age          0.02157749  0.03859719</code></pre>
</div>
</div>
</section>
</section>
<section id="prediction" class="level1" data-number="10">
<h1 data-number="10"><span class="header-section-number">10</span> Prediction</h1>
<section id="predict-the-log-odds" class="level2" data-number="10.1">
<h2 data-number="10.1" class="anchored" data-anchor-id="predict-the-log-odds"><span class="header-section-number">10.1</span> Predict the log odds</h2>
<p>For model 1 (mod1) that use VGAM::vglm function previously</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
vglm(formula = cat_fbs2 ~ gender, family = multinomial, data = clean_data)

Coefficients: 
              Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept):1 -2.13590    0.07515 -28.423  &lt; 2e-16 ***
(Intercept):2 -1.29294    0.05264 -24.564  &lt; 2e-16 ***
gendermale:1   0.07934    0.12802   0.620  0.53545    
gendermale:2   0.23841    0.08652   2.756  0.00586 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Names of linear predictors: log(mu[,1]/mu[,3]), log(mu[,2]/mu[,3])

Residual deviance: 5560.465 on 7088 degrees of freedom

Log-likelihood: -2780.233 on 7088 degrees of freedom

Number of Fisher scoring iterations: 5 

No Hauck-Donner effect found in any of the estimates


Reference group is level  3  of the response</code></pre>
</div>
</div>
<p>The predicted log odds for the first 6 observations:</p>
<ul>
<li>The predicted log odds for diabetes vs normal group in column 1</li>
<li>The predicted log odds for prediabetes vs normal group in column 2</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(<span class="fu">predict.vgam</span>(mod1, <span class="at">type =</span> <span class="st">'link'</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  log(mu[,1]/mu[,3]) log(mu[,2]/mu[,3])
1          -2.135898          -1.292939
2          -2.056563          -1.054531
3          -2.135898          -1.292939
4          -2.056563          -1.054531
5          -2.135898          -1.292939
6          -2.135898          -1.292939</code></pre>
</div>
</div>
<p>We can verify these prediction manually. For example the calculation for:</p>
<ol type="1">
<li>the 1st observation log odds</li>
<li>the 4th observation log odds</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(clean_data)[<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>,]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 24
  codesub    age hpt   smoking dmdx  height weight waist   hip msbpr mdbpr hba1c
  &lt;fct&gt;    &lt;dbl&gt; &lt;fct&gt; &lt;fct&gt;   &lt;fct&gt;  &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1 R-S6151…    70 yes   never … no      1.54   40    76      61   135  80     5.2
2 MAA6150…    20 no    still … no      1.74   54.6  83      62   105  58     5.3
3 M-M6163…    29 no    never … no      1.54   37    83      63    91  60     4.8
4 MFM6153…    25 no    still … no      1.6    48.4  83.5    64   117  68.5   4.8
# ℹ 12 more variables: fbs &lt;dbl&gt;, mogtt1h &lt;dbl&gt;, mogtt2h &lt;dbl&gt;, totchol &lt;dbl&gt;,
#   ftrigliz &lt;dbl&gt;, hdl &lt;dbl&gt;, ldl &lt;dbl&gt;, gender &lt;fct&gt;, crural &lt;fct&gt;,
#   cat_fbs &lt;fct&gt;, cat_fbs2 &lt;fct&gt;, cat_fbs_relev &lt;fct&gt;</code></pre>
</div>
</div>
<p>The value for the - 1st observation are gender = female, 0 - 4th observation are gender = male, 1</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Patient 1, gender= female (0)</span></span>
<span id="cb82-2"><a href="#cb82-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Logit cat_fbs2= diabetes[1] vs normal [3]</span></span>
<span id="cb82-3"><a href="#cb82-3" aria-hidden="true" tabindex="-1"></a><span class="sc">-</span><span class="fl">2.13590</span> <span class="sc">+</span> (<span class="fl">0.07934</span><span class="sc">*</span><span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -2.1359</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Logit cat_fbs2 = prediabetes [2] vs normal [3]</span></span>
<span id="cb84-2"><a href="#cb84-2" aria-hidden="true" tabindex="-1"></a><span class="sc">-</span><span class="fl">1.29294</span><span class="sc">+</span> (<span class="fl">0.23841</span><span class="sc">*</span><span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -1.29294</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Patient 4, gender male (1)</span></span>
<span id="cb86-2"><a href="#cb86-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Logit cat_fbs2 = diabetes [1] vs normal [3]</span></span>
<span id="cb86-3"><a href="#cb86-3" aria-hidden="true" tabindex="-1"></a><span class="sc">-</span><span class="fl">2.13590</span> <span class="sc">+</span> (<span class="fl">0.07934</span><span class="sc">*</span><span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -2.05656</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb88"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Logit cat_fbs2 = prediabetes [2] vs normal [3]</span></span>
<span id="cb88-2"><a href="#cb88-2" aria-hidden="true" tabindex="-1"></a><span class="sc">-</span><span class="fl">1.29294</span><span class="sc">+</span> (<span class="fl">0.23841</span><span class="sc">*</span><span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -1.05453</code></pre>
</div>
</div>
</section>
<section id="predict-the-probability" class="level2" data-number="10.2">
<h2 data-number="10.2" class="anchored" data-anchor-id="predict-the-probability"><span class="header-section-number">10.2</span> Predict the probability</h2>
<p>The predicted probability for the first 6 observation</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb90"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb90-1"><a href="#cb90-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(<span class="fu">predict.vgam</span>(mod1, <span class="at">type =</span> <span class="st">'response'</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    Diabetes Prediabetes    Normal
1 0.08483290   0.1970865 0.7180805
2 0.08663366   0.2359736 0.6773927
3 0.08483290   0.1970865 0.7180805
4 0.08663366   0.2359736 0.6773927
5 0.08483290   0.1970865 0.7180805
6 0.08483290   0.1970865 0.7180805</code></pre>
</div>
</div>
<p>Manual calculation for probability. Let us take the first observation where,</p>
<ol type="1">
<li>log odds for group diabetes = -2.13590</li>
<li>log odds for group prediabetes = -1.29294</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb92"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb92-1"><a href="#cb92-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Probability being in the reference group, cat_fbs2 = Normal [3]</span></span>
<span id="cb92-2"><a href="#cb92-2" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span><span class="sc">/</span>(<span class="dv">1</span><span class="sc">+</span> <span class="fu">exp</span>(<span class="sc">-</span><span class="fl">2.13590</span>)<span class="sc">+</span> <span class="fu">exp</span>(<span class="sc">-</span><span class="fl">1.29294</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.7180808</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb94"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb94-1"><a href="#cb94-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Probability being in the prediabetes group, cat_fbs2 = Prediabetes [2]</span></span>
<span id="cb94-2"><a href="#cb94-2" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="sc">-</span><span class="fl">1.29294</span>)<span class="sc">/</span> (<span class="dv">1</span><span class="sc">+</span> <span class="fu">exp</span>(<span class="sc">-</span><span class="fl">2.13590</span>)<span class="sc">+</span> <span class="fu">exp</span>(<span class="sc">-</span><span class="fl">1.29294</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1970864</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb96"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb96-1"><a href="#cb96-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Probability being in the diabetes group, cat_fbs2 = Diabaetes [1]</span></span>
<span id="cb96-2"><a href="#cb96-2" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="sc">-</span><span class="fl">2.13590</span>)<span class="sc">/</span> (<span class="dv">1</span><span class="sc">+</span> <span class="fu">exp</span>(<span class="sc">-</span><span class="fl">2.13590</span>)<span class="sc">+</span> <span class="fu">exp</span>(<span class="sc">-</span><span class="fl">1.29294</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.08483279</code></pre>
</div>
</div>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>